-- 0111 — housekeeping for the two INFO advisories that 0107/0109 introduced.

-- The new FK on paddle_webhook_events.user_id needs a covering index, otherwise
-- every users-row delete has to seq-scan the webhook table to check the
-- constraint (same class of fix as 0105 did for the other three FKs).
create index if not exists paddle_webhook_events_user_fk_idx
  on public.paddle_webhook_events (user_id);

-- Give the 0107 reversal table a key so it stops showing up as an unkeyed table
-- in the linter, and so a restore can address a single row.
alter table public.users_orphan_backup_0107
  add column if not exists id bigint generated by default as identity;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.users_orphan_backup_0107'::regclass and contype = 'p'
  ) then
    alter table public.users_orphan_backup_0107
      add constraint users_orphan_backup_0107_pkey primary key (id);
  end if;
end $$;
