// Generated by scripts/build-hustlek-approved-opening.cjs. Approved bytes and raw timings are preserved.
const SOURCES: Record<string, number> = {
  "background": require("../../../assets/opening/hustlek-approved-261002/images/background.png") as number,
  "telescope": require("../../../assets/opening/hustlek-approved-261002/images/telescope.png") as number,
  "walk-03": require("../../../assets/opening/hustlek-approved-261002/frames/walk-03.png") as number,
  "walk-04": require("../../../assets/opening/hustlek-approved-261002/frames/walk-04.png") as number,
  "walk-05": require("../../../assets/opening/hustlek-approved-261002/frames/walk-05.png") as number,
  "walk-06": require("../../../assets/opening/hustlek-approved-261002/frames/walk-06.png") as number,
  "walk-07": require("../../../assets/opening/hustlek-approved-261002/frames/walk-07.png") as number,
  "walk-08": require("../../../assets/opening/hustlek-approved-261002/frames/walk-08.png") as number,
  "turn-1": require("../../../assets/opening/hustlek-approved-261002/frames/turn-1.png") as number,
  "turn-2": require("../../../assets/opening/hustlek-approved-261002/frames/turn-2.png") as number,
  "turn-3": require("../../../assets/opening/hustlek-approved-261002/frames/turn-3.png") as number,
  "adjust-1": require("../../../assets/opening/hustlek-approved-261002/frames/adjust-1.png") as number,
  "adjust-2": require("../../../assets/opening/hustlek-approved-261002/frames/adjust-2.png") as number,
  "adjust-3": require("../../../assets/opening/hustlek-approved-261002/frames/adjust-3.png") as number,
  "wrist-1": require("../../../assets/opening/hustlek-approved-261002/frames/wrist-1.png") as number,
  "wrist-2": require("../../../assets/opening/hustlek-approved-261002/frames/wrist-2.png") as number,
  "observe-1": require("../../../assets/opening/hustlek-approved-261002/frames/observe-1.png") as number,
  "observe-2": require("../../../assets/opening/hustlek-approved-261002/frames/observe-2.png") as number,
  "observe-3": require("../../../assets/opening/hustlek-approved-261002/frames/observe-3.png") as number,
  "polaris-24": require("../../../assets/opening/hustlek-approved-261002/stars/polaris-24.png") as number,
  "polaris-32": require("../../../assets/opening/hustlek-approved-261002/stars/polaris-32.png") as number,
  "polaris-40": require("../../../assets/opening/hustlek-approved-261002/stars/polaris-40.png") as number,
  "grass-a": require("../../../assets/opening/hustlek-approved-261002/sounds/grass-a.wav") as number,
  "grass-b": require("../../../assets/opening/hustlek-approved-261002/sounds/grass-b.wav") as number,
  "ratchet": require("../../../assets/opening/hustlek-approved-261002/sounds/ratchet.wav") as number,
  "ping": require("../../../assets/opening/hustlek-approved-261002/sounds/ping.wav") as number,
};

export type ApprovedOpeningStage = "walk" | "turn" | "adjust" | "observe" | "contact" | "pan" | "center" | "ping" | "end";
export type ApprovedSoundSource = "grass" | "ratchet" | "ping";
type Point = { x: number; y: number };
type Placement = Point & { scale: number };
export type ApprovedOpeningFrame = { id: string; group: ApprovedOpeningStage; width: number; height: number; placement?: Placement; layer?: string };
type Item = { uid: string; frameId: string; stage: ApprovedOpeningStage; durationMs: number; rawDurationMs: number; scenePhase?: ApprovedOpeningStage };
export type ApprovedOpeningCue = { sourceId: ApprovedSoundSource; variantId: string; variantIndex: number; volume: number; atMs: number; key: string; enabled: boolean };
type Config = {
  totalMs: number;
  sourceAssetSet: string;
  scene: { width: number; height: number; character: Placement; telescope: Placement };
  phone: { width: number; height: number };
  approach: { startX: number; endX: number; grid: number };
  opening: { cameraStart: Point; cameraEnd: Point; cameraEasing: string; grid: number; star: Point & { frames: { id: string; size: number }[]; twinkle: { durationMs: number; flashColor: string; sparkleColor: string } } };
  frames: ApprovedOpeningFrame[];
  sequence: Item[];
  cues: ApprovedOpeningCue[];
  sounds: { grassA: string; grassB: string; ratchet: string; ping: string };
  twinkleEnabled: boolean;
};
type Settings = { schemaVersion: 4; assetSet: string; mode: string; parameters: { soundEnabled: boolean; twinkleEnabled: boolean; volume: number }; actionSettings: Record<ApprovedOpeningStage, { speed: number; volume: number; soundEnabled: boolean }>; sequences: Record<string, { uid: string; frameId: string; durationMs: number; included: boolean }[]>; scenePhases: { id: ApprovedOpeningStage; durationMs: number; included: boolean }[]; speed: number; loop: boolean; qaNote: string };
export type ApprovedViewportLayout = { width: number; height: number; unit: number; viewWidth: number; viewHeight: number; foregroundScale: number; starScale: number; anchor: Point; start: Point; end: Point };
export type ApprovedOpeningBox = { left: number; top: number; width: number; height: number; source: number; zIndex?: number };
export type ApprovedTwinkleRect = { left: number; top: number; width: number; height: number; color: string; alpha: number };

export const APPROVED_OPENING_CONFIG = require("../../../assets/opening/hustlek-approved-261002/manifest.json") as Config;
export const APPROVED_OPENING_SETTINGS = require("../../../assets/opening/hustlek-approved-261002/approved-settings.json") as Settings;
export const APPROVED_OPENING_SEQUENCE: readonly Item[] = APPROVED_OPENING_CONFIG.sequence;
export const APPROVED_OPENING_DURATION_MS = APPROVED_OPENING_CONFIG.totalMs;
export const APPROVED_OPENING_IMAGE_SOURCES = Object.entries(SOURCES).filter(([id]) => !Object.values(APPROVED_OPENING_CONFIG.sounds).includes(id)).map(([, source]) => source);
export const imageSources = APPROVED_OPENING_IMAGE_SOURCES;
export const APPROVED_OPENING_ASSETS = {
  background: SOURCES.background,
  telescope: SOURCES.telescope,
  frames: Object.fromEntries(APPROVED_OPENING_CONFIG.frames.map(frame => [frame.id, SOURCES[frame.id]])),
  stars: { 24: SOURCES["polaris-24"], 32: SOURCES["polaris-32"], 40: SOURCES["polaris-40"] },
  sounds: { grassA: SOURCES["grass-a"], grassB: SOURCES["grass-b"], ratchet: SOURCES.ratchet, ping: SOURCES.ping },
  audio: { grassA: SOURCES["grass-a"], grassB: SOURCES["grass-b"], ratchet: SOURCES.ratchet, ping: SOURCES.ping },
};

const starts: number[] = [];
let startMs = 0;
for (const item of APPROVED_OPENING_SEQUENCE) { starts.push(startMs); startMs += item.durationMs; }
function phaseRange(id: string): { startMs: number; durationMs: number } | null {
  const index = APPROVED_OPENING_SEQUENCE.findIndex(item => item.scenePhase === id);
  return index < 0 ? null : { startMs: starts[index], durationMs: APPROVED_OPENING_SEQUENCE[index].durationMs };
}

export function getApprovedOpeningFrame(elapsedMs: number) {
  if (!Number.isFinite(elapsedMs)) throw new Error("Opening time must be finite.");
  const time = Math.max(0, Math.min(APPROVED_OPENING_DURATION_MS, elapsedMs));
  const finished = elapsedMs >= APPROVED_OPENING_DURATION_MS;
  let index = APPROVED_OPENING_SEQUENCE.length - 1;
  if (!finished) index = APPROVED_OPENING_SEQUENCE.findIndex((item, i) => time < starts[i] + item.durationMs - 1e-8);
  if (index < 0) index = 0;
  const item = APPROVED_OPENING_SEQUENCE[index];
  const frame = APPROVED_OPENING_CONFIG.frames.find(frame => frame.id === item.frameId)!;
  return { frameId: frame.id, frame: { ...frame, source: SOURCES[frame.id] }, index, stage: item.stage, item, elapsedMs: time, finished };
}

export function cameraAt(elapsedMs: number): Point {
  const { opening } = APPROVED_OPENING_CONFIG;
  const pan = phaseRange("pan"), start = opening.cameraStart, end = opening.cameraEnd;
  if (!pan) { const target = phaseRange("center") || phaseRange("ping"); return target && elapsedMs >= target.startMs ? { ...end } : { ...start }; }
  if (elapsedMs <= pan.startMs) return { ...start };
  const p = Math.max(0, Math.min(1, (elapsedMs - pan.startMs) / pan.durationMs));
  const ease = p < 0.5 ? 4 * p * p * p : 1 - Math.pow(-2 * p + 2, 3) / 2;
  return { x: Math.round((start.x + (end.x - start.x) * ease) / opening.grid) * opening.grid, y: Math.round((start.y + (end.y - start.y) * ease) / opening.grid) * opening.grid };
}

export function viewportLayout(width: number, height: number): ApprovedViewportLayout {
  if (!Number.isFinite(width) || !Number.isFinite(height) || width <= 0 || height <= 0) throw new Error("Viewport dimensions must be positive.");
  const { phone, scene, opening } = APPROVED_OPENING_CONFIG, star = opening.star;
  const maxWidth = Math.min(phone.width, star.x * 2, (scene.width - star.x) * 2), maxHeight = Math.min(scene.height, star.y * 2, (scene.height - star.y) * 2);
  const unit = Math.max(width / maxWidth, height / maxHeight), viewWidth = width / unit, viewHeight = height / unit, anchor = { x: star.x, y: opening.cameraStart.y + phone.height };
  return { width, height, unit, viewWidth, viewHeight, foregroundScale: Math.min(1, viewWidth / phone.width, viewHeight / 360), starScale: Math.min(1, viewWidth / 128, viewHeight / 128), anchor, start: { x: star.x - viewWidth / 2, y: anchor.y - viewHeight }, end: { x: star.x - viewWidth / 2, y: Math.max(0, star.y - viewHeight / 2) } };
}

export function cameraForViewport(camera: Point, layout: ApprovedViewportLayout): Point {
  const { phone, opening } = APPROVED_OPENING_CONFIG;
  if (layout.viewWidth === phone.width && layout.viewHeight === phone.height) return { ...camera };
  const start = opening.cameraStart, end = opening.cameraEnd;
  const progress = end.y === start.y ? 0 : Math.max(0, Math.min(1, (camera.y - start.y) / (end.y - start.y)));
  return { x: layout.start.x, y: Math.max(0, layout.start.y + (layout.end.y - layout.start.y) * progress) };
}

export function foregroundForViewport(placement: Placement, layout: ApprovedViewportLayout): Placement {
  const { anchor, foregroundScale: q } = layout;
  return { ...placement, x: anchor.x + (placement.x - anchor.x) * q, y: anchor.y + (placement.y - anchor.y) * q, scale: placement.scale * q };
}

function placementAt(frame: ApprovedOpeningFrame, time: number, index: number): Placement {
  const config = APPROVED_OPENING_CONFIG, placement = { ...(frame.placement || config.scene.character) };
  let prefix = 0;
  while (prefix < APPROVED_OPENING_SEQUENCE.length && APPROVED_OPENING_SEQUENCE[prefix].stage === "walk") prefix++;
  if (frame.group === "walk" && index < prefix) {
    const total = prefix < starts.length ? starts[prefix] : APPROVED_OPENING_DURATION_MS;
    const ratio = total ? Math.min(1, time / total) : 1;
    placement.x = config.approach.startX + Math.round((config.approach.endX - config.approach.startX) * ratio / config.approach.grid) * config.approach.grid;
  }
  return placement;
}

function placementForViewport(frame: ApprovedOpeningFrame, time: number, index: number, layout: ApprovedViewportLayout): Placement {
  const original = placementAt(frame, time, index), placement = foregroundForViewport(original, layout);
  let prefix = 0;
  while (prefix < APPROVED_OPENING_SEQUENCE.length && APPROVED_OPENING_SEQUENCE[prefix].stage === "walk") prefix++;
  if (frame.group === "walk" && index < prefix) {
    const route = APPROVED_OPENING_CONFIG.approach, q = layout.foregroundScale;
    const start = layout.start.x - (frame.width * original.scale + 16) * q, end = layout.anchor.x + (route.endX - layout.anchor.x) * q;
    const progress = route.endX === route.startX ? 1 : Math.max(0, Math.min(1, (original.x - route.startX) / (route.endX - route.startX)));
    placement.x = start + (end - start) * progress;
  }
  return placement;
}

export function twinkleAt(elapsedMs: number): { x: number; y: number; width: number; height: number; color: string; alpha: number }[] {
  const ping = phaseRange("ping"), { twinkle } = APPROVED_OPENING_CONFIG.opening.star;
  if (!APPROVED_OPENING_CONFIG.twinkleEnabled || !ping || elapsedMs < ping.startMs || elapsedMs >= ping.startMs + ping.durationMs) return [];
  const local = (elapsedMs - ping.startMs) / ping.durationMs * 900;
  const rects = [];
  if (local < 120 || (local >= 360 && local < 480)) for (const [x, y, width, height] of [[-12, -4, 24, 8], [-4, -12, 8, 24], [-4, -4, 8, 8]]) rects.push({ x, y, width, height, color: twinkle.flashColor, alpha: 1 });
  if ((local >= 40 && local < 180) || (local >= 400 && local < 600)) {
    const offset = local < 180 ? 28 : 40;
    for (const [x, y] of [[-offset, -offset], [offset, -offset], [-offset, offset], [offset, offset]]) rects.push({ x: x < 0 ? x : x - 4, y: y < 0 ? y : y - 4, width: 4, height: 4, color: twinkle.sparkleColor, alpha: 1 });
  }
  return rects;
}

// One fixed box for every character frame (Simon localhost QA 2026-10-04).
// The observe frames are 480 px wide and the others 400 px. While the box
// followed each frame, it widened at adjust-3 -> observe-1 one paint before the
// new image was on screen, so adjust-3 was drawn 1.2x wide for a frame (web
// 13-15 ms, Android emulator 72 ms) and read as a sudden eyepiece pose. The
// slot keeps the widest frame's size; LoadingScreen draws each frame inside it
// with contain + top-left, which lands exactly on `character` below.
const CHARACTER_SLOT = { width: Math.max(...APPROVED_OPENING_CONFIG.frames.map(frame => frame.width)), height: Math.max(...APPROVED_OPENING_CONFIG.frames.map(frame => frame.height)) };

export function getApprovedOpeningScene(elapsedMs: number, width: number, height: number) {
  const view = getApprovedOpeningFrame(elapsedMs), config = APPROVED_OPENING_CONFIG, layout = viewportLayout(width, height);
  const camera = cameraForViewport(cameraAt(view.elapsedMs), layout), unit = layout.unit;
  const placement = placementForViewport(view.frame, view.elapsedMs, view.index, layout);
  const telescope = foregroundForViewport(config.scene.telescope, layout);
  const star = config.opening.star, ping = phaseRange("ping");
  const starFrame = ping && view.elapsedMs >= ping.startMs && view.elapsedMs < ping.startMs + ping.durationMs ? star.frames[Math.min(star.frames.length - 1, Math.floor((view.elapsedMs - ping.startMs) / ping.durationMs * star.frames.length))] : star.frames[0];
  const starUnit = layout.starScale * unit;
  const box = (p: Placement, w: number, h: number, source: number, zIndex: number): ApprovedOpeningBox => ({ left: (p.x - camera.x) * unit, top: (p.y - camera.y) * unit, width: w * p.scale * unit, height: h * p.scale * unit, source, zIndex });
  const characterZ = view.frame.layer === "behind-telescope" ? 1 : 3;
  return { ...view, layout, camera,
    background: { left: -camera.x * unit, top: -camera.y * unit, width: config.scene.width * unit, height: config.scene.height * unit, source: SOURCES.background, zIndex: 0 },
    character: box(placement, view.frame.width, view.frame.height, view.frame.source, characterZ),
    characterSlot: box(placement, CHARACTER_SLOT.width, CHARACTER_SLOT.height, view.frame.source, characterZ),
    telescope: box(telescope, 256, 256, SOURCES.telescope, 2),
    star: { left: (star.x - camera.x) * unit - starFrame.size * starUnit / 2, top: (star.y - camera.y) * unit - starFrame.size * starUnit / 2, width: starFrame.size * starUnit, height: starFrame.size * starUnit, source: SOURCES[starFrame.id], zIndex: 4 },
    twinkle: { left: (star.x - camera.x) * unit - 64 * starUnit, top: (star.y - camera.y) * unit - 64 * starUnit, width: 128 * starUnit, height: 128 * starUnit, unit: starUnit, rects: twinkleAt(view.elapsedMs).map(rect => ({ left: (rect.x + 64) * starUnit, top: (rect.y + 64) * starUnit, width: rect.width * starUnit, height: rect.height * starUnit, color: rect.color, alpha: rect.alpha })) as ApprovedTwinkleRect[] },
  };
}

/** Latest event per family on delayed ticks; seeking backwards is silent. */
export function getApprovedOpeningCues(fromMs: number, toMs: number): ApprovedOpeningCue[] {
  if (!Number.isFinite(fromMs) || !Number.isFinite(toMs) || toMs <= fromMs) return [];
  const latest: Partial<Record<ApprovedSoundSource, ApprovedOpeningCue>> = {};
  for (const cue of APPROVED_OPENING_CONFIG.cues) if (cue.enabled && cue.atMs > fromMs && cue.atMs <= toMs + 1e-8) latest[cue.sourceId] = cue;
  return Object.values(latest).sort((a, b) => a.atMs - b.atMs);
}

// Loading in use order (Simon localhost QA 2026-10-03: no loading screen before
// the opening). Waiting for all 22 images showed "PolaScope 불러오는 중" for
// about 1.9 s on localhost and 9.5 s on a 4G-like link, because every image
// was requested at once and the first scene finished together with the last.
// The screen now loads images in the order the opening first shows them and
// starts as soon as the current scene is in memory.
function approvedSceneSources(elapsedMs: number): number[] {
  const scene = getApprovedOpeningScene(elapsedMs, 390, 844);
  return [scene.background.source, scene.telescope.source, scene.star.source, scene.character.source];
}

/** Every opening image, in the order the opening first shows it. */
export const APPROVED_OPENING_IMAGES_IN_USE_ORDER: readonly number[] = (() => {
  const order: number[] = [];
  const add = (source: number) => { if (!order.includes(source)) order.push(source); };
  for (let time = 0; time <= APPROVED_OPENING_DURATION_MS; time += 20) approvedSceneSources(time).forEach(add);
  approvedSceneSources(APPROVED_OPENING_DURATION_MS).forEach(add);
  APPROVED_OPENING_IMAGE_SOURCES.forEach(add);
  return order;
})();

/** Images the opening shows from elapsedMs up to lookaheadMs later (sampled every 50 ms). */
export function approvedOpeningSourcesNeeded(elapsedMs: number, lookaheadMs = 0): number[] {
  const needed: number[] = [];
  const end = Math.min(APPROVED_OPENING_DURATION_MS, Math.max(0, elapsedMs) + Math.max(0, lookaheadMs));
  for (let time = Math.max(0, Math.min(elapsedMs, APPROVED_OPENING_DURATION_MS)); ; time += 50) {
    for (const source of approvedSceneSources(Math.min(time, end))) if (!needed.includes(source)) needed.push(source);
    if (time >= end) break;
  }
  return needed;
}
