// Auto-generated by supabase MCP (generate_typescript_types).
// Regenerated after migrations 0022_wiki_rag + 0023_chat_usage were applied
// to the remote project. Do not edit manually.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  public: {
    Tables: {
      ai_audit_log: {
        Row: {
          created_at: string
          id: string
          latency_ms: number
          model_used: string
          output_hash: string
          prompt_hash: string
          safety_zone: Database["public"]["Enums"]["safety_zone"]
          user_id: string | null
          vertex_backend: boolean
        }
        Insert: {
          created_at?: string
          id?: string
          latency_ms: number
          model_used: string
          output_hash: string
          prompt_hash: string
          safety_zone: Database["public"]["Enums"]["safety_zone"]
          user_id?: string | null
          vertex_backend: boolean
        }
        Update: {
          created_at?: string
          id?: string
          latency_ms?: number
          model_used?: string
          output_hash?: string
          prompt_hash?: string
          safety_zone?: Database["public"]["Enums"]["safety_zone"]
          user_id?: string | null
          vertex_backend?: boolean
        }
        Relationships: [
          {
            foreignKeyName: "ai_audit_log_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      chat_usage: {
        Row: {
          count: number
          day: string
          updated_at: string
          user_id: string
        }
        Insert: {
          count?: number
          day: string
          updated_at?: string
          user_id: string
        }
        Update: {
          count?: number
          day?: string
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "chat_usage_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      crisis_events: {
        Row: {
          classifier_confidence: number | null
          created_at: string
          cssrs_level: number | null
          id: string
          locale: string
          notes: string | null
          occurred_at: string
          resolved: boolean
          routing_template_version: string
          trigger_categories: string[]
          user_id_hash: string | null
          zone: string
        }
        Insert: {
          classifier_confidence?: number | null
          created_at?: string
          cssrs_level?: number | null
          id?: string
          locale: string
          notes?: string | null
          occurred_at?: string
          resolved?: boolean
          routing_template_version: string
          trigger_categories?: string[]
          user_id_hash?: string | null
          zone: string
        }
        Update: {
          classifier_confidence?: number | null
          created_at?: string
          cssrs_level?: number | null
          id?: string
          locale?: string
          notes?: string | null
          occurred_at?: string
          resolved?: boolean
          routing_template_version?: string
          trigger_categories?: string[]
          user_id_hash?: string | null
          zone?: string
        }
        Relationships: []
      }
      knowledge_sources: {
        Row: {
          added_by: string | null
          age_range: string | null
          application_notes: string | null
          authors: string[] | null
          created_at: string
          doi: string | null
          framework: string | null
          id: string
          locale: string | null
          summary_en: string | null
          summary_ko: string | null
          title: string
          url: string | null
          verified_at: string | null
          verified_by: string | null
        }
        Insert: {
          added_by?: string | null
          age_range?: string | null
          application_notes?: string | null
          authors?: string[] | null
          created_at?: string
          doi?: string | null
          framework?: string | null
          id?: string
          locale?: string | null
          summary_en?: string | null
          summary_ko?: string | null
          title: string
          url?: string | null
          verified_at?: string | null
          verified_by?: string | null
        }
        Update: {
          added_by?: string | null
          age_range?: string | null
          application_notes?: string | null
          authors?: string[] | null
          created_at?: string
          doi?: string | null
          framework?: string | null
          id?: string
          locale?: string | null
          summary_en?: string | null
          summary_ko?: string | null
          title?: string
          url?: string | null
          verified_at?: string | null
          verified_by?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "knowledge_sources_added_by_fkey"
            columns: ["added_by"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "knowledge_sources_verified_by_fkey"
            columns: ["verified_by"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      memorized_patterns: {
        Row: {
          created_at: string
          evidence_batches: string[]
          id: string
          pattern_kind: string
          recorded_zone: string
          summary: string
          triggers: string[]
          user_id: string
        }
        Insert: {
          created_at?: string
          evidence_batches?: string[]
          id?: string
          pattern_kind: string
          recorded_zone: string
          summary: string
          triggers?: string[]
          user_id: string
        }
        Update: {
          created_at?: string
          evidence_batches?: string[]
          id?: string
          pattern_kind?: string
          recorded_zone?: string
          summary?: string
          triggers?: string[]
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "memorized_patterns_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      personas: {
        Row: {
          created_at: string
          id: string
          markdown_export: string | null
          patterns: Json | null
          traits: Json
          user_id: string
          values: Json | null
          version: number
        }
        Insert: {
          created_at?: string
          id?: string
          markdown_export?: string | null
          patterns?: Json | null
          traits: Json
          user_id: string
          values?: Json | null
          version: number
        }
        Update: {
          created_at?: string
          id?: string
          markdown_export?: string | null
          patterns?: Json | null
          traits?: Json
          user_id?: string
          values?: Json | null
          version?: number
        }
        Relationships: [
          {
            foreignKeyName: "personas_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      records: {
        Row: {
          ai_followup: Json | null
          audit_period: string | null
          body: string
          conclusion: string | null
          created_at: string
          id: string
          kind: Database["public"]["Enums"]["record_kind"]
          prompt: string | null
          self_context_id: string | null
          summary: string | null
          tags: string[]
          topic: string | null
          updated_at: string
          user_id: string
        }
        Insert: {
          ai_followup?: Json | null
          audit_period?: string | null
          body: string
          conclusion?: string | null
          created_at?: string
          id?: string
          kind: Database["public"]["Enums"]["record_kind"]
          prompt?: string | null
          self_context_id?: string | null
          summary?: string | null
          tags?: string[]
          topic?: string | null
          updated_at?: string
          user_id: string
        }
        Update: {
          ai_followup?: Json | null
          audit_period?: string | null
          body?: string
          conclusion?: string | null
          created_at?: string
          id?: string
          kind?: Database["public"]["Enums"]["record_kind"]
          prompt?: string | null
          self_context_id?: string | null
          summary?: string | null
          tags?: string[]
          topic?: string | null
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "records_self_context_id_fkey"
            columns: ["self_context_id"]
            isOneToOne: false
            referencedRelation: "self_contexts"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "records_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      revenue_events: {
        Row: {
          amount_cents: number
          created_at: string
          currency: string
          customer_relation_type: Database["public"]["Enums"]["customer_relation"]
          external_id: string | null
          id: string
          is_related_party: boolean
          month_bucket: string
          occurred_at: string
          source: string
          user_id: string | null
        }
        Insert: {
          amount_cents: number
          created_at?: string
          currency: string
          customer_relation_type: Database["public"]["Enums"]["customer_relation"]
          external_id?: string | null
          id?: string
          is_related_party: boolean
          month_bucket: string
          occurred_at: string
          source: string
          user_id?: string | null
        }
        Update: {
          amount_cents?: number
          created_at?: string
          currency?: string
          customer_relation_type?: Database["public"]["Enums"]["customer_relation"]
          external_id?: string | null
          id?: string
          is_related_party?: boolean
          month_bucket?: string
          occurred_at?: string
          source?: string
          user_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "revenue_events_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      self_contexts: {
        Row: {
          context_kind: string
          created_at: string
          id: string
          label: string
          user_id: string
        }
        Insert: {
          context_kind: string
          created_at?: string
          id?: string
          label: string
          user_id: string
        }
        Update: {
          context_kind?: string
          created_at?: string
          id?: string
          label?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "self_contexts_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      sources: {
        Row: {
          captured_at: string
          frontmatter: Json
          id: string
          ingested: boolean
          ingested_at: string | null
          kind: string
          simon_relevance: number | null
          source_url: string | null
          storage_path: string
          tags: string[]
          title: string
          user_id: string
        }
        Insert: {
          captured_at?: string
          frontmatter?: Json
          id?: string
          ingested?: boolean
          ingested_at?: string | null
          kind: string
          simon_relevance?: number | null
          source_url?: string | null
          storage_path: string
          tags?: string[]
          title: string
          user_id: string
        }
        Update: {
          captured_at?: string
          frontmatter?: Json
          id?: string
          ingested?: boolean
          ingested_at?: string | null
          kind?: string
          simon_relevance?: number | null
          source_url?: string | null
          storage_path?: string
          tags?: string[]
          title?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "sources_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      testimonials: {
        Row: {
          approved_for_public: boolean
          body: string
          consent_given_at: string
          consent_ip: unknown
          created_at: string
          id: string
          locale: string
          share_with_judges_flag: boolean
          user_id: string
        }
        Insert: {
          approved_for_public?: boolean
          body: string
          consent_given_at: string
          consent_ip?: unknown
          created_at?: string
          id?: string
          locale: string
          share_with_judges_flag?: boolean
          user_id: string
        }
        Update: {
          approved_for_public?: boolean
          body?: string
          consent_given_at?: string
          consent_ip?: unknown
          created_at?: string
          id?: string
          locale?: string
          share_with_judges_flag?: boolean
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "testimonials_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      users: {
        Row: {
          birth_date: string
          coachmarks_seen: Json
          consent_share_with_judges: boolean
          created_at: string
          email: string
          id: string
          judge_mode: boolean
          locale: string
          onboarding_quest_completed_at: string | null
          subscription_expires_at: string | null
          subscription_provider: string | null
          subscription_tier: string
          total_xp: number
          updated_at: string
        }
        Insert: {
          birth_date: string
          coachmarks_seen?: Json
          consent_share_with_judges?: boolean
          created_at?: string
          email: string
          id: string
          judge_mode?: boolean
          locale?: string
          onboarding_quest_completed_at?: string | null
          subscription_expires_at?: string | null
          subscription_provider?: string | null
          subscription_tier?: string
          total_xp?: number
          updated_at?: string
        }
        Update: {
          birth_date?: string
          coachmarks_seen?: Json
          consent_share_with_judges?: boolean
          created_at?: string
          email?: string
          id?: string
          judge_mode?: boolean
          locale?: string
          onboarding_quest_completed_at?: string | null
          subscription_expires_at?: string | null
          subscription_provider?: string | null
          subscription_tier?: string
          total_xp?: number
          updated_at?: string
        }
        Relationships: []
      }
      wiki_links: {
        Row: {
          created_at: string
          from_page: string
          to_page: string
          user_id: string
        }
        Insert: {
          created_at?: string
          from_page: string
          to_page: string
          user_id: string
        }
        Update: {
          created_at?: string
          from_page?: string
          to_page?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "wiki_links_from_fk"
            columns: ["user_id", "from_page"]
            isOneToOne: false
            referencedRelation: "wiki_pages"
            referencedColumns: ["user_id", "id"]
          },
          {
            foreignKeyName: "wiki_links_to_fk"
            columns: ["user_id", "to_page"]
            isOneToOne: false
            referencedRelation: "wiki_pages"
            referencedColumns: ["user_id", "id"]
          },
        ]
      }
      wiki_pages: {
        Row: {
          body_md: string
          created_at: string
          frontmatter: Json
          id: string
          kind: string
          slug: string
          source_id: string | null
          tags: string[]
          title: string
          updated_at: string
          user_id: string
        }
        Insert: {
          body_md?: string
          created_at?: string
          frontmatter?: Json
          id?: string
          kind: string
          slug: string
          source_id?: string | null
          tags?: string[]
          title: string
          updated_at?: string
          user_id: string
        }
        Update: {
          body_md?: string
          created_at?: string
          frontmatter?: Json
          id?: string
          kind?: string
          slug?: string
          source_id?: string | null
          tags?: string[]
          title?: string
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "wiki_pages_source_id_fkey"
            columns: ["source_id"]
            isOneToOne: false
            referencedRelation: "sources"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "wiki_pages_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      xp_events: {
        Row: {
          action: string
          created_at: string
          id: string
          level_after: number
          total_after: number
          user_id: string
          xp_delta: number
        }
        Insert: {
          action: string
          created_at?: string
          id?: string
          level_after: number
          total_after: number
          user_id: string
          xp_delta: number
        }
        Update: {
          action?: string
          created_at?: string
          id?: string
          level_after?: number
          total_after?: number
          user_id?: string
          xp_delta?: number
        }
        Relationships: [
          {
            foreignKeyName: "xp_events_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      xp_rules: {
        Row: {
          action: string
          once_only: boolean
          xp_value: number
        }
        Insert: {
          action: string
          once_only?: boolean
          xp_value: number
        }
        Update: {
          action?: string
          once_only?: boolean
          xp_value?: number
        }
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      award_xp: { Args: { p_action: string }; Returns: Json }
      bump_chat_usage: {
        Args: { p_day: string; p_user_id: string }
        Returns: number
      }
      level_for_xp: { Args: { xp: number }; Returns: number }
      show_limit: { Args: never; Returns: number }
      show_trgm: { Args: { "": string }; Returns: string[] }
    }
    Enums: {
      customer_relation:
        | "arms_length"
        | "family"
        | "friend"
        | "employee"
        | "self"
        | "unknown"
      record_kind: "journal" | "note" | "audit_response"
      safety_zone: "green" | "yellow" | "red"
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}
