// Auto-generated by supabase MCP (generate_typescript_types) on 2026-05-25.
// Do not edit manually. Regenerate via the Supabase MCP after schema changes.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  __InternalSupabase: { PostgrestVersion: "14.5" };
  public: {
    Tables: {
      ai_audit_log: {
        Row: {
          created_at: string;
          id: string;
          latency_ms: number;
          model_used: string;
          output_hash: string;
          prompt_hash: string;
          safety_zone: Database["public"]["Enums"]["safety_zone"];
          user_id: string | null;
          vertex_backend: boolean;
        };
        Insert: Omit<Database["public"]["Tables"]["ai_audit_log"]["Row"], "id" | "created_at"> &
          Partial<Pick<Database["public"]["Tables"]["ai_audit_log"]["Row"], "id" | "created_at">>;
        Update: Partial<Database["public"]["Tables"]["ai_audit_log"]["Row"]>;
      };
      crisis_events: {
        Row: {
          classifier_confidence: number | null;
          created_at: string;
          cssrs_level: number | null;
          id: string;
          locale: string;
          notes: string | null;
          occurred_at: string;
          resolved: boolean;
          routing_template_version: string;
          trigger_categories: string[];
          user_id_hash: string | null;
          zone: string;
        };
        Insert: Omit<Database["public"]["Tables"]["crisis_events"]["Row"], "id" | "created_at" | "occurred_at" | "resolved" | "trigger_categories"> &
          Partial<Pick<Database["public"]["Tables"]["crisis_events"]["Row"], "id" | "created_at" | "occurred_at" | "resolved" | "trigger_categories">>;
        Update: Partial<Database["public"]["Tables"]["crisis_events"]["Row"]>;
      };
      knowledge_sources: {
        Row: {
          added_by: string | null;
          age_range: string | null;
          application_notes: string | null;
          authors: string[] | null;
          created_at: string;
          doi: string | null;
          framework: string | null;
          id: string;
          locale: string | null;
          summary_en: string | null;
          summary_ko: string | null;
          title: string;
          url: string | null;
          verified_at: string | null;
          verified_by: string | null;
        };
        Insert: Partial<Database["public"]["Tables"]["knowledge_sources"]["Row"]> & { title: string };
        Update: Partial<Database["public"]["Tables"]["knowledge_sources"]["Row"]>;
      };
      personas: {
        Row: {
          created_at: string;
          id: string;
          markdown_export: string | null;
          patterns: Json | null;
          traits: Json;
          user_id: string;
          values: Json | null;
          version: number;
        };
        Insert: Omit<Database["public"]["Tables"]["personas"]["Row"], "id" | "created_at"> &
          Partial<Pick<Database["public"]["Tables"]["personas"]["Row"], "id" | "created_at">>;
        Update: Partial<Database["public"]["Tables"]["personas"]["Row"]>;
      };
      records: {
        Row: {
          ai_followup: Json | null;
          audit_period: string | null;
          body: string;
          created_at: string;
          id: string;
          kind: Database["public"]["Enums"]["record_kind"];
          prompt: string | null;
          updated_at: string;
          user_id: string;
        };
        Insert: Omit<Database["public"]["Tables"]["records"]["Row"], "id" | "created_at" | "updated_at"> &
          Partial<Pick<Database["public"]["Tables"]["records"]["Row"], "id" | "created_at" | "updated_at">>;
        Update: Partial<Database["public"]["Tables"]["records"]["Row"]>;
      };
      revenue_events: {
        Row: {
          amount_cents: number;
          created_at: string;
          currency: string;
          customer_relation_type: Database["public"]["Enums"]["customer_relation"];
          external_id: string | null;
          id: string;
          is_related_party: boolean;
          month_bucket: string;
          occurred_at: string;
          source: string;
          user_id: string | null;
        };
        Insert: Omit<Database["public"]["Tables"]["revenue_events"]["Row"], "id" | "created_at"> &
          Partial<Pick<Database["public"]["Tables"]["revenue_events"]["Row"], "id" | "created_at">>;
        Update: Partial<Database["public"]["Tables"]["revenue_events"]["Row"]>;
      };
      testimonials: {
        Row: {
          approved_for_public: boolean;
          body: string;
          consent_given_at: string;
          consent_ip: unknown;
          created_at: string;
          id: string;
          locale: string;
          share_with_judges_flag: boolean;
          user_id: string;
        };
        Insert: Omit<Database["public"]["Tables"]["testimonials"]["Row"], "id" | "created_at" | "approved_for_public" | "share_with_judges_flag" | "consent_ip"> &
          Partial<Pick<Database["public"]["Tables"]["testimonials"]["Row"], "id" | "created_at" | "approved_for_public" | "share_with_judges_flag" | "consent_ip">>;
        Update: Partial<Database["public"]["Tables"]["testimonials"]["Row"]>;
      };
      users: {
        Row: {
          birth_date: string;
          consent_share_with_judges: boolean;
          created_at: string;
          email: string;
          id: string;
          judge_mode: boolean;
          locale: string;
          updated_at: string;
        };
        Insert: Omit<Database["public"]["Tables"]["users"]["Row"], "created_at" | "updated_at" | "consent_share_with_judges" | "judge_mode" | "locale"> &
          Partial<Pick<Database["public"]["Tables"]["users"]["Row"], "created_at" | "updated_at" | "consent_share_with_judges" | "judge_mode" | "locale">>;
        Update: Partial<Database["public"]["Tables"]["users"]["Row"]>;
      };
    };
    Functions: {
      admin_exec_sql: { Args: { sql_text: string }; Returns: Json };
    };
    Enums: {
      customer_relation: "arms_length" | "family" | "friend" | "employee" | "self" | "unknown";
      record_kind: "journal" | "note" | "audit_response";
      safety_zone: "green" | "yellow" | "red";
    };
  };
};
