// Auto-generated by supabase MCP (generate_typescript_types).
// Regenerated 2026-06-10 against the remote project with migrations through
// 0043 applied — the previous snapshot predated esm_responses,
// gemini_spend_daily, guardian_consents, clipper_templates, consent_records
// and knowledge_sources.added_by (cycle-3 audit findings 6/7).
// Do not edit manually.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  public: {
    Tables: {
      ai_audit_log: {
        Row: {
          created_at: string
          id: string
          latency_ms: number
          model_used: string
          output_hash: string
          prompt_hash: string
          safety_zone: Database["public"]["Enums"]["safety_zone"]
          user_id: string | null
          vertex_backend: boolean
        }
        Insert: {
          created_at?: string
          id?: string
          latency_ms: number
          model_used: string
          output_hash: string
          prompt_hash: string
          safety_zone: Database["public"]["Enums"]["safety_zone"]
          user_id?: string | null
          vertex_backend: boolean
        }
        Update: {
          created_at?: string
          id?: string
          latency_ms?: number
          model_used?: string
          output_hash?: string
          prompt_hash?: string
          safety_zone?: Database["public"]["Enums"]["safety_zone"]
          user_id?: string | null
          vertex_backend?: boolean
        }
        Relationships: [
          {
            foreignKeyName: "ai_audit_log_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      chat_usage: {
        Row: {
          count: number
          day: string
          updated_at: string
          user_id: string
        }
        Insert: {
          count?: number
          day: string
          updated_at?: string
          user_id: string
        }
        Update: {
          count?: number
          day?: string
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "chat_usage_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      clipper_templates: {
        Row: {
          ai_properties: Json
          base_kind: string
          created_at: string
          default_tags: string[]
          id: string
          is_shared: boolean
          name: Json
          owner_id: string
          slug: string
          target_category: string
          triggers: string[]
          updated_at: string
          what: Json
          wiki_target: string
        }
        Insert: {
          ai_properties?: Json
          base_kind: string
          created_at?: string
          default_tags?: string[]
          id?: string
          is_shared?: boolean
          name?: Json
          owner_id: string
          slug: string
          target_category?: string
          triggers?: string[]
          updated_at?: string
          what?: Json
          wiki_target?: string
        }
        Update: {
          ai_properties?: Json
          base_kind?: string
          created_at?: string
          default_tags?: string[]
          id?: string
          is_shared?: boolean
          name?: Json
          owner_id?: string
          slug?: string
          target_category?: string
          triggers?: string[]
          updated_at?: string
          what?: Json
          wiki_target?: string
        }
        Relationships: [
          {
            foreignKeyName: "clipper_templates_owner_id_fkey"
            columns: ["owner_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      consent_records: {
        Row: {
          age_band: string
          consent_version: string
          created_at: string
          id: string
          ip_hash: string | null
          llm_processing_ack: boolean
          locale: string
          minor_tier: string | null
          optional_consents: Json
          overseas_transfer_ack: boolean
          policy_version: string
          purposes: Json
          required_ack: boolean
          sensitive_data_ack: boolean
          terms_version: string
          ua_hash: string | null
          user_id: string
        }
        Insert: {
          age_band: string
          consent_version: string
          created_at?: string
          id?: string
          ip_hash?: string | null
          llm_processing_ack?: boolean
          locale: string
          minor_tier?: string | null
          optional_consents?: Json
          overseas_transfer_ack?: boolean
          policy_version: string
          purposes?: Json
          required_ack?: boolean
          sensitive_data_ack?: boolean
          terms_version: string
          ua_hash?: string | null
          user_id: string
        }
        Update: {
          age_band?: string
          consent_version?: string
          created_at?: string
          id?: string
          ip_hash?: string | null
          llm_processing_ack?: boolean
          locale?: string
          minor_tier?: string | null
          optional_consents?: Json
          overseas_transfer_ack?: boolean
          policy_version?: string
          purposes?: Json
          required_ack?: boolean
          sensitive_data_ack?: boolean
          terms_version?: string
          ua_hash?: string | null
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "consent_records_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      crisis_events: {
        Row: {
          classifier_confidence: number | null
          created_at: string
          cssrs_level: number | null
          id: string
          locale: string
          notes: string | null
          occurred_at: string
          resolved: boolean
          routing_template_version: string
          trigger_categories: string[]
          user_id_hash: string | null
          zone: string
        }
        Insert: {
          classifier_confidence?: number | null
          created_at?: string
          cssrs_level?: number | null
          id?: string
          locale: string
          notes?: string | null
          occurred_at?: string
          resolved?: boolean
          routing_template_version: string
          trigger_categories?: string[]
          user_id_hash?: string | null
          zone: string
        }
        Update: {
          classifier_confidence?: number | null
          created_at?: string
          cssrs_level?: number | null
          id?: string
          locale?: string
          notes?: string | null
          occurred_at?: string
          resolved?: boolean
          routing_template_version?: string
          trigger_categories?: string[]
          user_id_hash?: string | null
          zone?: string
        }
        Relationships: []
      }
      esm_responses: {
        Row: {
          context_tags: string[]
          created_at: string
          id: string
          prompt_kind: string
          scale_value: number | null
          user_id: string
        }
        Insert: {
          context_tags?: string[]
          created_at?: string
          id?: string
          prompt_kind: string
          scale_value?: number | null
          user_id: string
        }
        Update: {
          context_tags?: string[]
          created_at?: string
          id?: string
          prompt_kind?: string
          scale_value?: number | null
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "esm_responses_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      gemini_spend_daily: {
        Row: {
          calls: number
          day: string
          updated_at: string
          user_id: string
        }
        Insert: {
          calls?: number
          day: string
          updated_at?: string
          user_id: string
        }
        Update: {
          calls?: number
          day?: string
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "gemini_spend_daily_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      guardian_consents: {
        Row: {
          child_user_id: string
          consent_method: string
          consent_scope: string
          guardian_email: string
          guardian_name: string | null
          id: string
          requested_at: string
          revoked_at: string | null
          verification_token_hash: string | null
          verified_at: string | null
        }
        Insert: {
          child_user_id: string
          consent_method?: string
          consent_scope?: string
          guardian_email: string
          guardian_name?: string | null
          id?: string
          requested_at?: string
          revoked_at?: string | null
          verification_token_hash?: string | null
          verified_at?: string | null
        }
        Update: {
          child_user_id?: string
          consent_method?: string
          consent_scope?: string
          guardian_email?: string
          guardian_name?: string | null
          id?: string
          requested_at?: string
          revoked_at?: string | null
          verification_token_hash?: string | null
          verified_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "guardian_consents_child_user_id_fkey"
            columns: ["child_user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      knowledge_sources: {
        Row: {
          added_by: string | null
          age_range: string | null
          application_notes: string | null
          authors: string[] | null
          created_at: string
          doi: string | null
          framework: string | null
          id: string
          locale: string | null
          summary_en: string | null
          summary_ko: string | null
          title: string
          url: string | null
          verified_at: string | null
          verified_by: string | null
        }
        Insert: {
          added_by?: string | null
          age_range?: string | null
          application_notes?: string | null
          authors?: string[] | null
          created_at?: string
          doi?: string | null
          framework?: string | null
          id?: string
          locale?: string | null
          summary_en?: string | null
          summary_ko?: string | null
          title: string
          url?: string | null
          verified_at?: string | null
          verified_by?: string | null
        }
        Update: {
          added_by?: string | null
          age_range?: string | null
          application_notes?: string | null
          authors?: string[] | null
          created_at?: string
          doi?: string | null
          framework?: string | null
          id?: string
          locale?: string | null
          summary_en?: string | null
          summary_ko?: string | null
          title?: string
          url?: string | null
          verified_at?: string | null
          verified_by?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "knowledge_sources_added_by_fkey"
            columns: ["added_by"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "knowledge_sources_verified_by_fkey"
            columns: ["verified_by"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      memorized_patterns: {
        Row: {
          created_at: string
          evidence_batches: string[]
          id: string
          pattern_kind: string
          recorded_zone: string
          summary: string
          triggers: string[]
          user_id: string
        }
        Insert: {
          created_at?: string
          evidence_batches?: string[]
          id?: string
          pattern_kind: string
          recorded_zone: string
          summary: string
          triggers?: string[]
          user_id: string
        }
        Update: {
          created_at?: string
          evidence_batches?: string[]
          id?: string
          pattern_kind?: string
          recorded_zone?: string
          summary?: string
          triggers?: string[]
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "memorized_patterns_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      health_samples: {
        Row: {
          created_at: string | null
          ended_at: string | null
          external_id: string | null
          id: string
          metadata: Json
          metric_type: string
          source: string
          started_at: string
          unit: string
          user_id: string
          value: number
        }
        Insert: {
          created_at?: string | null
          ended_at?: string | null
          external_id?: string | null
          id?: string
          metadata?: Json
          metric_type: string
          source: string
          started_at: string
          unit: string
          user_id: string
          value: number
        }
        Update: {
          created_at?: string | null
          ended_at?: string | null
          external_id?: string | null
          id?: string
          metadata?: Json
          metric_type?: string
          source?: string
          started_at?: string
          unit?: string
          user_id?: string
          value?: number
        }
        Relationships: [
          {
            foreignKeyName: "health_samples_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      ops_routine_logs: {
        Row: {
          completed_on: string
          created_at: string
          id: string
          routine_id: string
          source_sample_id: string | null
          user_id: string
        }
        Insert: {
          completed_on: string
          created_at?: string
          id?: string
          routine_id: string
          source_sample_id?: string | null
          user_id: string
        }
        Update: {
          completed_on?: string
          created_at?: string
          id?: string
          routine_id?: string
          source_sample_id?: string | null
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "ops_routine_logs_routine_id_fkey"
            columns: ["routine_id"]
            isOneToOne: false
            referencedRelation: "ops_routines"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "ops_routine_logs_source_sample_id_fkey"
            columns: ["source_sample_id"]
            isOneToOne: false
            referencedRelation: "health_samples"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "ops_routine_logs_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      news_items: {
        Row: {
          created_at: string | null
          id: string
          published_at: string | null
          snippet: string | null
          source: string
          summary: string | null
          title: string
          url: string
          user_id: string
        }
        Insert: {
          created_at?: string | null
          id?: string
          published_at?: string | null
          snippet?: string | null
          source: string
          summary?: string | null
          title: string
          url: string
          user_id: string
        }
        Update: {
          created_at?: string | null
          id?: string
          published_at?: string | null
          snippet?: string | null
          source?: string
          summary?: string | null
          title?: string
          url?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "news_items_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      ops_routines: {
        Row: {
          active: boolean
          checklist: Json
          created_at: string
          domain_id: string
          duration_minutes: number | null
          id: string
          reason: string | null
          recurrence: string
          reminder_time: string | null
          title: string
          user_id: string
          weekday: number | null
        }
        Insert: {
          active?: boolean
          checklist?: Json
          created_at?: string
          domain_id: string
          duration_minutes?: number | null
          id?: string
          reason?: string | null
          recurrence?: string
          reminder_time?: string | null
          title: string
          user_id: string
          weekday?: number | null
        }
        Update: {
          active?: boolean
          checklist?: Json
          created_at?: string
          domain_id?: string
          duration_minutes?: number | null
          id?: string
          reason?: string | null
          recurrence?: string
          reminder_time?: string | null
          title?: string
          user_id?: string
          weekday?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "ops_routines_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      srs_cards: {
        Row: {
          back: string
          created_at: string | null
          deck: string | null
          difficulty: number | null
          due: string
          elapsed_days: number | null
          front: string
          id: string
          lapses: number
          last_review: string | null
          reps: number
          scheduled_days: number | null
          stability: number | null
          state: number
          user_id: string
        }
        Insert: {
          back: string
          created_at?: string | null
          deck?: string | null
          difficulty?: number | null
          due: string
          elapsed_days?: number | null
          front: string
          id?: string
          lapses?: number
          last_review?: string | null
          reps?: number
          scheduled_days?: number | null
          stability?: number | null
          state?: number
          user_id: string
        }
        Update: {
          back?: string
          created_at?: string | null
          deck?: string | null
          difficulty?: number | null
          due?: string
          elapsed_days?: number | null
          front?: string
          id?: string
          lapses?: number
          last_review?: string | null
          reps?: number
          scheduled_days?: number | null
          stability?: number | null
          state?: number
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "srs_cards_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      srs_reviews: {
        Row: {
          card_id: string
          created_at: string | null
          id: string
          rating: number
          reviewed_on: string
          user_id: string
        }
        Insert: {
          card_id: string
          created_at?: string | null
          id?: string
          rating: number
          reviewed_on: string
          user_id: string
        }
        Update: {
          card_id?: string
          created_at?: string | null
          id?: string
          rating?: number
          reviewed_on?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "srs_reviews_card_id_fkey"
            columns: ["card_id"]
            isOneToOne: false
            referencedRelation: "srs_cards"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "srs_reviews_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      personas: {
        Row: {
          created_at: string
          id: string
          markdown_export: string | null
          patterns: Json | null
          traits: Json
          user_id: string
          values: Json | null
          version: number
        }
        Insert: {
          created_at?: string
          id?: string
          markdown_export?: string | null
          patterns?: Json | null
          traits: Json
          user_id: string
          values?: Json | null
          version: number
        }
        Update: {
          created_at?: string
          id?: string
          markdown_export?: string | null
          patterns?: Json | null
          traits?: Json
          user_id?: string
          values?: Json | null
          version?: number
        }
        Relationships: [
          {
            foreignKeyName: "personas_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      records: {
        Row: {
          ai_followup: Json | null
          audit_period: string | null
          body: string
          conclusion: string | null
          created_at: string
          id: string
          kind: Database["public"]["Enums"]["record_kind"]
          prompt: string | null
          self_context_id: string | null
          summary: string | null
          tags: string[]
          topic: string | null
          updated_at: string
          user_id: string
        }
        Insert: {
          ai_followup?: Json | null
          audit_period?: string | null
          body: string
          conclusion?: string | null
          created_at?: string
          id?: string
          kind: Database["public"]["Enums"]["record_kind"]
          prompt?: string | null
          self_context_id?: string | null
          summary?: string | null
          tags?: string[]
          topic?: string | null
          updated_at?: string
          user_id: string
        }
        Update: {
          ai_followup?: Json | null
          audit_period?: string | null
          body?: string
          conclusion?: string | null
          created_at?: string
          id?: string
          kind?: Database["public"]["Enums"]["record_kind"]
          prompt?: string | null
          self_context_id?: string | null
          summary?: string | null
          tags?: string[]
          topic?: string | null
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "records_self_context_id_fkey"
            columns: ["self_context_id"]
            isOneToOne: false
            referencedRelation: "self_contexts"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "records_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      revenue_events: {
        Row: {
          amount_cents: number
          created_at: string
          currency: string
          customer_relation_type: Database["public"]["Enums"]["customer_relation"]
          external_id: string | null
          id: string
          is_related_party: boolean
          month_bucket: string
          occurred_at: string
          source: string
          user_id: string | null
        }
        Insert: {
          amount_cents: number
          created_at?: string
          currency: string
          customer_relation_type: Database["public"]["Enums"]["customer_relation"]
          external_id?: string | null
          id?: string
          is_related_party: boolean
          month_bucket: string
          occurred_at: string
          source: string
          user_id?: string | null
        }
        Update: {
          amount_cents?: number
          created_at?: string
          currency?: string
          customer_relation_type?: Database["public"]["Enums"]["customer_relation"]
          external_id?: string | null
          id?: string
          is_related_party?: boolean
          month_bucket?: string
          occurred_at?: string
          source?: string
          user_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "revenue_events_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      self_contexts: {
        Row: {
          context_kind: string
          created_at: string
          id: string
          label: string
          user_id: string
        }
        Insert: {
          context_kind: string
          created_at?: string
          id?: string
          label: string
          user_id: string
        }
        Update: {
          context_kind?: string
          created_at?: string
          id?: string
          label?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "self_contexts_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      sources: {
        Row: {
          captured_at: string
          frontmatter: Json
          id: string
          ingested: boolean
          ingested_at: string | null
          kind: string
          simon_relevance: number | null
          source_url: string | null
          storage_path: string
          tags: string[]
          title: string
          user_id: string
        }
        Insert: {
          captured_at?: string
          frontmatter?: Json
          id?: string
          ingested?: boolean
          ingested_at?: string | null
          kind: string
          simon_relevance?: number | null
          source_url?: string | null
          storage_path: string
          tags?: string[]
          title: string
          user_id: string
        }
        Update: {
          captured_at?: string
          frontmatter?: Json
          id?: string
          ingested?: boolean
          ingested_at?: string | null
          kind?: string
          simon_relevance?: number | null
          source_url?: string | null
          storage_path?: string
          tags?: string[]
          title?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "sources_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      testimonials: {
        Row: {
          approved_for_public: boolean
          body: string
          consent_given_at: string
          consent_ip: unknown
          created_at: string
          id: string
          locale: string
          share_with_judges_flag: boolean
          user_id: string
        }
        Insert: {
          approved_for_public?: boolean
          body: string
          consent_given_at: string
          consent_ip?: unknown
          created_at?: string
          id?: string
          locale: string
          share_with_judges_flag?: boolean
          user_id: string
        }
        Update: {
          approved_for_public?: boolean
          body?: string
          consent_given_at?: string
          consent_ip?: unknown
          created_at?: string
          id?: string
          locale?: string
          share_with_judges_flag?: boolean
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "testimonials_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      users: {
        Row: {
          account_status: string
          birth_date: string
          coachmarks_seen: Json
          consent_share_with_judges: boolean
          created_at: string
          email: string
          id: string
          judge_mode: boolean
          locale: string
          minor_tier: string | null
          onboarding_quest_completed_at: string | null
          privacy_prefs: Json
          subscription_expires_at: string | null
          subscription_provider: string | null
          subscription_tier: string
          total_xp: number
          updated_at: string
        }
        Insert: {
          account_status?: string
          birth_date: string
          coachmarks_seen?: Json
          consent_share_with_judges?: boolean
          created_at?: string
          email: string
          id: string
          judge_mode?: boolean
          locale?: string
          minor_tier?: string | null
          onboarding_quest_completed_at?: string | null
          privacy_prefs?: Json
          subscription_expires_at?: string | null
          subscription_provider?: string | null
          subscription_tier?: string
          total_xp?: number
          updated_at?: string
        }
        Update: {
          account_status?: string
          birth_date?: string
          coachmarks_seen?: Json
          consent_share_with_judges?: boolean
          created_at?: string
          email?: string
          id?: string
          judge_mode?: boolean
          locale?: string
          minor_tier?: string | null
          onboarding_quest_completed_at?: string | null
          privacy_prefs?: Json
          subscription_expires_at?: string | null
          subscription_provider?: string | null
          subscription_tier?: string
          total_xp?: number
          updated_at?: string
        }
        Relationships: []
      }
      wiki_links: {
        Row: {
          created_at: string
          from_page: string
          to_page: string
          user_id: string
        }
        Insert: {
          created_at?: string
          from_page: string
          to_page: string
          user_id: string
        }
        Update: {
          created_at?: string
          from_page?: string
          to_page?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "wiki_links_from_fk"
            columns: ["user_id", "from_page"]
            isOneToOne: false
            referencedRelation: "wiki_pages"
            referencedColumns: ["user_id", "id"]
          },
          {
            foreignKeyName: "wiki_links_to_fk"
            columns: ["user_id", "to_page"]
            isOneToOne: false
            referencedRelation: "wiki_pages"
            referencedColumns: ["user_id", "id"]
          },
        ]
      }
      wiki_pages: {
        Row: {
          body_md: string
          created_at: string
          frontmatter: Json
          id: string
          kind: string
          slug: string
          source_id: string | null
          tags: string[]
          title: string
          updated_at: string
          user_id: string
        }
        Insert: {
          body_md?: string
          created_at?: string
          frontmatter?: Json
          id?: string
          kind: string
          slug: string
          source_id?: string | null
          tags?: string[]
          title: string
          updated_at?: string
          user_id: string
        }
        Update: {
          body_md?: string
          created_at?: string
          frontmatter?: Json
          id?: string
          kind?: string
          slug?: string
          source_id?: string | null
          tags?: string[]
          title?: string
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "wiki_pages_source_id_fkey"
            columns: ["source_id"]
            isOneToOne: false
            referencedRelation: "sources"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "wiki_pages_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      xp_events: {
        Row: {
          action: string
          created_at: string
          id: string
          level_after: number
          total_after: number
          user_id: string
          xp_delta: number
        }
        Insert: {
          action: string
          created_at?: string
          id?: string
          level_after: number
          total_after: number
          user_id: string
          xp_delta: number
        }
        Update: {
          action?: string
          created_at?: string
          id?: string
          level_after?: number
          total_after?: number
          user_id?: string
          xp_delta?: number
        }
        Relationships: [
          {
            foreignKeyName: "xp_events_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      xp_rules: {
        Row: {
          action: string
          once_only: boolean
          xp_value: number
        }
        Insert: {
          action: string
          once_only?: boolean
          xp_value: number
        }
        Update: {
          action?: string
          once_only?: boolean
          xp_value?: number
        }
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      award_xp: { Args: { p_action: string }; Returns: Json }
      bump_chat_usage: {
        Args: { p_day: string; p_user_id: string }
        Returns: number
      }
      bump_chat_usage_if_under_cap: {
        Args: { p_cap: number; p_day: string; p_user_id: string }
        Returns: number
      }
      bump_gemini_spend: {
        Args: { p_cap: number; p_day: string; p_user_id: string }
        Returns: number
      }
      level_for_xp: { Args: { xp: number }; Returns: number }
      log_ai_audit: {
        Args: {
          p_latency_ms: number
          p_model_used: string
          p_output_hash: string
          p_prompt_hash: string
          p_safety_zone: string
          p_vertex_backend: boolean
        }
        Returns: undefined
      }
      log_crisis_event: {
        Args: {
          p_classifier_confidence: number
          p_cssrs_level: number
          p_locale: string
          p_routing_template_version: string
          p_trigger_categories: string[]
        }
        Returns: undefined
      }
      show_limit: { Args: never; Returns: number }
      show_trgm: { Args: { "": string }; Returns: string[] }
    }
    Enums: {
      customer_relation:
        | "arms_length"
        | "family"
        | "friend"
        | "employee"
        | "self"
        | "unknown"
      record_kind: "journal" | "note" | "audit_response"
      safety_zone: "green" | "yellow" | "red"
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {
      customer_relation: [
        "arms_length",
        "family",
        "friend",
        "employee",
        "self",
        "unknown",
      ],
      record_kind: ["journal", "note", "audit_response"],
      safety_zone: ["green", "yellow", "red"],
    },
  },
} as const
