// Shared client/Edge regression inputs. No model or network is involved.
const INVISIBLE_SCAN_CHARACTERS = ["\u200b", "\u200c", "\u200d", "\u2060", "\ufeff", "\u00ad"];
const INSERTED_SCAN_SEPARATORS = [".", "-", "_", "\u00b7", "\u2022", "\u2027", "\u2010", "\u2011", "\u2012", "\u2013", "\u2014", "\u2015"];
const SCAN_APOSTROPHES = ["\u2018", "\u2019", "\u02bc", "\uff07"];

// Joining all whitespace invents a crisis term across these everyday words.
export const SPACE_SENSITIVE_BENIGN_CONTEXTS = [
  "혼자 살고 싶어.",
  "매일 자 살펴봐.",
  "의자 살 때 크기를 확인해요.",
  "각자 살아온 이야기를 나눠요.",
  "모자 살 돈을 모았어요.",
  "죽 고르는 일을 하고 싶어요.",
] as const;

export const BENIGN_CRISIS_CONTEXTS = [
  ...SPACE_SENSITIVE_BENIGN_CONTEXTS,
  ...SCAN_APOSTROPHES.flatMap((apostrophe) => [
    `I${apostrophe}m not suicidal.`,
    `I don${apostrophe}t want to die.`,
  ]),
  "I want.to dine.",
  "오늘은 죽.고기는 내일 먹어요.",
  "내가 욕심은 있는데, 잠은 좀 자고 싶어. 오늘 은 3시간 정도 잔거 같아.",
  "아니... 자살하려는 건 아냐... 날 뭘로 보는거야",
  "아니... 자살하려는 건 아냐... 날 뭘로 보는거야?",
  "아니요. 저는 자살하려는 게 아니에요.",
  "자살 생각은 없어.",
  "자해할 생각은 없어요.",
  "I'm not suicidal.",
  "I don't want to die.",
  "오늘 일을 끝내고 싶어요.",
  "업무를 빨리 끝내고 싶어도 잠부터 자요.",
  "작업을 마저 끝낼 거예요.",
  "프로젝트를 끝내고 싶은 마음은 알지만 오늘은 쉬어요.",
  "공부를 끝내고 싶다면 잠부터 충분히 자요.",
  "오늘 끝내고 싶은 일이 있어도 먼저 잠을 자요.",
  "끝내고 싶은 업무가 있더라도 오늘은 쉬어요.",
  "자살하려는 건 아냐".normalize("NFD"),
  "오늘 일을\n끝내고\u3000싶어요.",
  "일을 끝내고 싶고, 공부를 끝낼거예요.",
] as const;

export const RISK_OR_UNRESOLVED_CRISIS_CONTEXTS = [
  ...INVISIBLE_SCAN_CHARACTERS.flatMap((character) => [
    `지금 자${character}살하고 싶어.`,
    `I want to d${character}ie.`,
    // Removal must precede NFKC so separated NFD jamo compose again.
    `지금 ᄌ${character}ᅡ살하고 싶어.`,
  ]),
  ...INSERTED_SCAN_SEPARATORS.flatMap((separator) => [
    `지금 죽${separator}고 싶어.`,
    `지금 자${separator}살하고 싶어.`,
    `I want${separator}to${separator}die.`,
  ]),
  ...SCAN_APOSTROPHES.flatMap((apostrophe) => [
    `I${apostrophe}m not suicidal?`,
    `I don${apostrophe}t want to die, but I have pills ready.`,
    `I${apostrophe}m not suicidal. I have everything ready.`,
  ]),
  "I want.to die.",
  "지금 자._·살하고 싶어.",
  "I want._·to die.",
  "지금 죽.고.싶어.",
  "지금 죽 고 싶어.",
  "지금 죽\t고\n싶어.",
  "지금 죽 고싶어.",
  "지금 죽．고 싶어.",
  "Ｉ ｗａｎｔ．ｔｏ ｄｉｅ．",
  "자살하려는 건 아냐. 지금 죽.고 싶어.",
  "I’m not suicidal, but I want-to-die.",
  "I don’t want to die?",
  "I’m not suicidal. This is an unknown tail.",
  "My friend says I’m not suicidal.",
  "I’m not not suicidal.",
  "자살하려는 건 아니지만 지금 죽고 싶어.",
  "자살 생각이 없진 않아.",
  "자살을 안 할 자신이 없어.",
  "자살 생각은 없어?",
  "자살하려는 건 아냐?",
  "I'm not suicidal?",
  "친구가 자살하려는 건 아냐.",
  "자살하려는 건 아냐. 자살할 계획이 있어.",
  "자살하려는 건 아냐. 그래도 영영 잠들고 싶어.",
  "자살하려는 건 아냐. 약을 이미 많이 먹었어.",
  "자살하려는 건 아냐. 약을 모아 두었어.",
  "자살하려는 건 아냐. 지금 옥상에 있어.",
  "자살하려는 건 아냐. 준비는 다 했어.",
  "자살하려는 건 아냐. 그렇지만 모르겠어.",
  "자살하려는 건 아냐고 말했지만 사실이 아니야.",
  "자살하려는 건 아냐. 이 뒤의 문장은 허용되지 않은 정정이야.",
  "자해할 생각은 없어요. 하지만 이미 다쳤어요.",
  "I'm not suicidal, but I want to die.",
  "I don't want to die, but I've already taken too much medication.",
  "I'm not suicidal. I have everything ready.",
  "오늘 일을 끝내고 싶어요. 죽고 싶어요.",
  "일을 끝내고 싶어요. 모든 걸 끝내고 싶어요.",
  "끝내고 싶은 일이 있어요. 그냥 다 끝낼 거예요.",
  "일을 끝내고 싶어. I want to die.",
  "일을 끝내고 싶어. 약을 이미 많이 먹었어.",
  "끝내고 싶은 일이 있어. 지금 옥상에 있어.",
  "일을 끝내고 싶어. 목에 줄을 걸었어.",
  "일을 끝내고 싶어. 번개탄을 피웠어.",
  "일을 끝내고 싶어. 더는 숨 쉬고 싶지 않아.",
  "일을 끝내고 싶고 목에 줄을 걸었어",
  "일을 끝내고 싶어, 번개탄을 피웠어",
  "목에 줄을 걸었고 일을 끝내고 싶어",
  "끝내고 싶은 일은 하나야, 나를 없애는 거야",
  "오늘 일을 끝내고 싶어 숨을 멈출 생각이야",
  "일을 끝내고 싶어. 처음 보는 후속 문장이야.",
  "처음 보는 앞선 문장이야. 일을 끝내고 싶어.",
  "내 삶의 일을 끝내고 싶어.",
  "오늘 밤 다 끝내고 싶어요.",
  "끝내고 싶다는 생각이 떠나지 않아요.",
  "끝내고 싶은 일생이야.",
  "내가 모두에게 짐이 되는 것 같아.",
  "자살하려는 건 아냐. 죽고 싶어.".normalize("NFD"),
] as const;
