// dds-styles: the shared deep-space design-screen stylesheet, extracted
// verbatim from DeepSpaceDesignScreens.tsx (P5 megafile split, tranche 1).
// One sheet, many screens - screens import { ddsStyles as styles } so call
// sites did not change. New screens should prefer their own local sheets.
import { StyleSheet } from "react-native";

import { colors, radius, spacing } from "@/theme/tokens";
import { deepSpace, withAlpha } from "@/lib/theme/tokens";
import { m3 } from "@/lib/theme/m3";
import { fontFamilies } from "@/theme/typography";

export const ddsStyles = StyleSheet.create({ root:{flex:1,backgroundColor:colors.bgDeep}, stars:{...StyleSheet.absoluteFill,overflow:'hidden'}, star:{position:'absolute',width:3,height:3,borderRadius:2,backgroundColor:colors.cyanSoft}, scroll:{padding:spacing.lg,paddingBottom:40,gap:spacing.md}, titleRow:{flexDirection:'row',alignItems:'center',gap:spacing.md,marginBottom:spacing.xs}, back:{color:colors.cyanSoft,fontSize:34,lineHeight:38,fontFamily:fontFamilies.readable}, title:{color:colors.textTitle,fontSize:18,}, subtitle:{color:colors.textLo,fontSize:11,}, card:{backgroundColor:colors.cardBg,borderWidth:1,borderColor:colors.border,borderRadius:radius.lg,padding:spacing.md,gap:spacing.sm}, graphCard:{height:332,overflow:'hidden'}, graphStage:{width:300,height:310,alignSelf:'center'}, centerCaption:{position:'absolute',left:0,right:0,top:156,textAlign:'center',color:colors.bgDeep,fontSize:11}, clusterLabel:{position:'absolute',color:colors.cyanSoft,fontSize:11}, ctaRow:{flexDirection:'row',gap:spacing.sm}, primary:{flex:1,alignItems:'center',justifyContent:'center',backgroundColor:colors.cyan,borderRadius:radius.md,paddingVertical:spacing.md}, primaryText:{color:colors.bgDeep,fontSize:13}, secondary:{flex:1,alignItems:'center',justifyContent:'center',borderColor:colors.borderHi,borderWidth:1,borderRadius:radius.md,paddingVertical:spacing.md}, secondaryText:{color:colors.cyanSoft,fontSize:13}, section:{color:colors.textTitle,fontSize:13,marginBottom:spacing.xs}, action:{minHeight:48,flexDirection:'row',alignItems:'center',justifyContent:'space-between',borderBottomWidth:1,borderBottomColor:colors.border,paddingVertical:spacing.sm}, actionLabel:{color:colors.textHi,fontSize:14}, actionValue:{color:colors.textLo,fontSize:12}, chev:{color:colors.cyanSoft,fontSize:22}, toggle:{width:42,height:24,borderRadius:12,backgroundColor:colors.border,justifyContent:'center',padding:3}, toggleOn:{backgroundColor:colors.cyan}, knob:{width:18,height:18,borderRadius:9,backgroundColor:colors.textLo}, knobOn:{alignSelf:'flex-end',backgroundColor:colors.bgDeep}, footer:{color:colors.textLo,textAlign:'center',fontSize:12,}, center:{alignItems:'center',gap:spacing.sm}, prompt:{color:colors.textHi,fontSize:16,textAlign:'center'}, avatar:{width:92,height:92,borderRadius:46,borderWidth:1,borderColor:colors.borderHi,alignItems:'center',justifyContent:'center',backgroundColor:colors.cardBg}, danger:{alignSelf:'center',padding:spacing.md},dangerText:{color:colors.clay,fontSize:13}, lead:{color:colors.textMid,fontSize:14,textAlign:'center'}, authHero:{alignItems:'center',paddingTop:32,gap:spacing.md}, big:{color:colors.textTitle,fontSize:24,}, input:{borderWidth:1,borderColor:colors.border,borderRadius:radius.md,padding:spacing.md,color:colors.textHi,fontFamily:fontFamilies.readable,backgroundColor:colors.bgDeep}, link:{color:colors.cyanSoft,textAlign:'center',paddingTop:spacing.sm}, mail:{fontSize:44,color:colors.cyanSoft}, codeRow:{flexDirection:'row',justifyContent:'center',gap:spacing.xs}, codeCell:{width:40,height:48,borderRadius:radius.sm,borderWidth:1,borderColor:colors.borderHi,backgroundColor:colors.cardBg}, pill:{borderWidth:1,borderColor:colors.border,borderRadius:radius.pill,paddingHorizontal:spacing.sm,paddingVertical:spacing.xs},pillText:{color:colors.cyanSoft,fontFamily:m3.font.mono,fontSize:8}, compareRow:{flexDirection:'row',alignItems:'center',justifyContent:'center',gap:spacing.lg,paddingVertical:spacing.sm}, compareCol:{alignItems:'center',gap:spacing.xs}, compareNum:{color:colors.textMid,fontSize:30}, compareNumHi:{color:colors.cyan}, compareCap:{color:colors.textLo,fontSize:11}, delta:{color:colors.mint,textAlign:'center',fontSize:13}, statRow:{flexDirection:'row',gap:spacing.sm}, statBox:{flex:1,alignItems:'center',gap:spacing.xs,backgroundColor:colors.cardBg,borderWidth:1,borderColor:colors.border,borderRadius:radius.lg,paddingVertical:spacing.md}, statNum:{color:colors.cyan,fontSize:28}, statCap:{color:colors.textLo,fontSize:11}, sizeRow:{flexDirection:'row',alignItems:'center',gap:spacing.sm}, sizeCap:{color:colors.textLo,fontSize:12}, sizeCapLg:{color:colors.textHi,fontSize:18}, sizeTrack:{flex:1,height:4,borderRadius:2,backgroundColor:colors.border,justifyContent:'center'}, sizeKnob:{width:18,height:18,borderRadius:9,backgroundColor:colors.cyan,marginLeft:'46%'}, searchBox:{backgroundColor:colors.cardBg,borderWidth:1,borderColor:colors.border,borderRadius:radius.md,paddingHorizontal:spacing.md,paddingVertical:spacing.md}, searchText:{color:colors.textLo,fontSize:13}, planPro:{borderColor:colors.borderHi}, planHead:{flexDirection:'row',alignItems:'center',justifyContent:'space-between'}, planName:{color:colors.textTitle,fontSize:15}, planBadge:{color:colors.bgDeep,backgroundColor:colors.cyan,fontSize:8,paddingHorizontal:spacing.sm,paddingVertical:3,borderRadius:radius.sm,overflow:'hidden'}, planPrice:{color:colors.textHi,fontSize:22,marginVertical:spacing.xs}, planPer:{color:colors.textLo,fontSize:12}, planFeat:{color:colors.cyanSoft,fontSize:13,}, planFeatDim:{color:colors.textMid,fontSize:13,}, plansLoading:{alignItems:'center',gap:spacing.sm,paddingVertical:spacing.lg}, planBtnBusy:{opacity:0.5}, planSupportLink:{color:colors.cyan,fontSize:13,marginTop:spacing.sm}, planError:{color:colors.amber,fontSize:12,textAlign:'center'}, planRestore:{alignItems:'center',justifyContent:'center',borderWidth:1,borderColor:colors.border,borderRadius:radius.md,paddingVertical:spacing.md}, planRestoreText:{color:colors.textMid,fontSize:13},
 // ── Paywall (① 페이월) deep-space canon ──
 paySoulGlow:{position:'absolute',top:54,left:'50%',width:240,height:240,marginLeft:-120,borderRadius:120,backgroundColor:withAlpha(deepSpace.soul,0.14)},
 payStars:{...StyleSheet.absoluteFill,height:60,overflow:'hidden'},
 payStar:{position:'absolute',width:2,height:2,borderRadius:1,backgroundColor:withAlpha(deepSpace.accentSoft,0.5)},
 payStarSoul:{position:'absolute',width:2,height:2,borderRadius:1,backgroundColor:withAlpha(deepSpace.soul,0.45)},
 payHero:{paddingTop:spacing.sm,paddingBottom:spacing.xs,gap:spacing.md},
 payEyebrow:{color:deepSpace.soul,fontSize:8,letterSpacing:1.4},
 payTitle:{color:deepSpace.textHi,fontSize:24,lineHeight:34,fontWeight:'800',fontFamily:fontFamilies.readable},
 paySub:{color:withAlpha(deepSpace.accentSoft,0.66),fontSize:13.5,lineHeight:21,fontFamily:fontFamilies.readable},
 payCard:{borderWidth:1,borderColor:withAlpha(deepSpace.accent,0.18),borderRadius:radius.lg,backgroundColor:withAlpha(deepSpace.accent,0.04),padding:spacing.md,gap:spacing.sm},
 payCardFree:{borderColor:withAlpha(deepSpace.accent,0.18),backgroundColor:withAlpha(deepSpace.accent,0.04)},
 payCardPlus:{borderWidth:1.5,borderColor:withAlpha(deepSpace.accent,0.7),backgroundColor:withAlpha(deepSpace.accent,0.08),shadowColor:deepSpace.accent,shadowOpacity:0.3,shadowRadius:18,shadowOffset:{width:0,height:8},elevation:6},
 payCardPro:{borderColor:withAlpha(deepSpace.soul,0.22),backgroundColor:withAlpha(deepSpace.soul,0.05)},
 payCardHead:{flexDirection:'row',alignItems:'baseline',justifyContent:'space-between'},
 payCardHeadPlus:{marginTop:spacing.xs},
 payRecTag:{position:'absolute',top:-9,left:spacing.md,color:deepSpace.onAccent,backgroundColor:deepSpace.accent,fontSize:7,letterSpacing:0.8,paddingHorizontal:9,paddingVertical:4,borderRadius:radius.sm,overflow:'hidden'},
 payTierNameFree:{color:deepSpace.accentBright,fontSize:15,fontWeight:'700',fontFamily:fontFamilies.readable},
 payTierNamePlus:{color:deepSpace.textHi,fontSize:17,fontWeight:'700',fontFamily:fontFamilies.readable},
 payTierNamePro:{color:deepSpace.soul,fontSize:15,fontWeight:'700',fontFamily:fontFamilies.readable},
 payPriceFree:{color:withAlpha(deepSpace.accentSoft,0.7),fontSize:14,fontFamily:fontFamilies.readable},
 payPricePlus:{color:deepSpace.accentBright,fontSize:14,fontFamily:fontFamilies.readable},
 payPricePro:{color:withAlpha(deepSpace.soul,0.85),fontSize:14,fontFamily:fontFamilies.readable},
 payPriceStrong:{color:deepSpace.accentBright,fontSize:16,fontWeight:'700'},
 payPriceStrongPro:{color:deepSpace.textHi,fontSize:15,fontWeight:'700'},
 payFeatList:{gap:7,marginTop:spacing.xs},
 payFeatRow:{flexDirection:'row',alignItems:'center',gap:9},
 payFeatFree:{flex:1,color:withAlpha(deepSpace.accentSoft,0.78),fontSize:12.5,fontFamily:fontFamilies.readable},
 payFeatPlus:{flex:1,color:deepSpace.accentBright,fontSize:12.5,fontFamily:fontFamilies.readable},
 payFeatPro:{flex:1,color:withAlpha(deepSpace.soul,0.85),fontSize:12.5,fontFamily:fontFamilies.readable},
 payActiveTag:{color:deepSpace.onAccent,backgroundColor:deepSpace.accent,fontSize:8,paddingHorizontal:spacing.sm,paddingVertical:3,borderRadius:radius.sm,overflow:'hidden'},
 payNameRow:{flexDirection:'row',alignItems:'baseline',gap:spacing.sm},
 payCurrentMarker:{color:deepSpace.accent,fontSize:9.5,letterSpacing:0.6,fontFamily:fontFamilies.readable},
 payFreeCaption:{color:withAlpha(deepSpace.accentSoft,0.7),fontSize:11,marginTop:spacing.xs,fontFamily:fontFamilies.readable},
 payCtaBlock:{marginTop:'auto',paddingTop:spacing.sm,gap:9},
 payTrustRow:{flexDirection:'row',alignItems:'center',justifyContent:'center',gap:6,marginBottom:spacing.xs},
 payTrust:{color:withAlpha(deepSpace.mint,0.85),fontSize:11.5,fontFamily:fontFamilies.readable},
 payPrimary:{minHeight:48,alignItems:'center',justifyContent:'center',backgroundColor:deepSpace.mint,borderRadius:radius.md,paddingVertical:spacing.md},
 payPrimaryDisabled:{opacity:0.5},
 payPrimaryText:{color:deepSpace.onMint,fontSize:16,fontWeight:'700',fontFamily:fontFamilies.readable},
 paySecondaryText:{color:withAlpha(deepSpace.accentSoft,0.6),fontSize:12.5,textAlign:'center',paddingVertical:11,fontFamily:fontFamilies.readable}, trendHead:{flexDirection:'row',alignItems:'center',justifyContent:'space-between'}, primaryWide:{flex:1.6}, filterRow:{flexDirection:'row',flexWrap:'wrap',gap:6}, fchip:{minHeight:44,justifyContent:'center',paddingVertical:6,paddingHorizontal:11,borderWidth:1,borderColor:colors.border,borderRadius:radius.sm}, fchipActive:{borderColor:colors.cyan,backgroundColor:colors.cardBg}, fchipViolet:{borderColor:colors.soulLine,backgroundColor:colors.cardBg}, fchipText:{color:colors.cyanSoft,fontSize:11}, fchipTextActive:{color:colors.textTitle}, fchipTextViolet:{color:colors.soul}, tlLabel:{color:colors.cyanDim,fontSize:11,letterSpacing:0.7,marginTop:spacing.sm}, tlGroup:{paddingLeft:16,borderLeftWidth:1,borderLeftColor:colors.border,gap:12,marginTop:spacing.xs}, tlRow:{flexDirection:'row',alignItems:'center',gap:9}, tlDot:{width:8,height:8,borderRadius:4,backgroundColor:colors.cyan}, tlDotDim:{backgroundColor:colors.cyanDim}, tlTitle:{flex:1,color:colors.textTitle,fontSize:12.5}, tlTitleDim:{color:colors.textMid}, tlTime:{color:colors.cyanDim,fontSize:10}, tlTagRow:{flexDirection:'row',paddingLeft:32}, tlTag:{color:colors.cyanDim,fontSize:10,letterSpacing:0.4,paddingHorizontal:6,paddingVertical:3,borderWidth:1,borderColor:colors.border,borderRadius:radius.sm}, progressRow:{flexDirection:'row',alignItems:'center',gap:10}, progressTrack:{flex:1,height:6,borderRadius:3,backgroundColor:colors.border,overflow:'hidden'}, progressFill:{height:'100%',borderRadius:3,backgroundColor:colors.cyan}, progressLabel:{color:colors.cyanSoft,fontSize:11}, triageCard:{borderColor:colors.borderHi}, triageMeta:{flexDirection:'row',alignItems:'center',gap:9}, metaLabel:{color:colors.cyanDim,fontSize:11,letterSpacing:0.5}, triageBody:{color:colors.textTitle,fontSize:13.5,}, footerLeft:{color:colors.textLo,fontSize:11,}, iconBtn:{width:46,paddingVertical:11,borderWidth:1,borderColor:colors.borderHi,borderRadius:radius.md,alignItems:'center',backgroundColor:colors.bgDeep}, iconBtnText:{fontSize:15}, queueItem:{flexDirection:'row',alignItems:'center',gap:9,paddingVertical:9,paddingHorizontal:11,borderWidth:1,borderColor:colors.border,borderRadius:radius.sm,backgroundColor:colors.cardBg}, queueItemDim:{opacity:0.6}, queueText:{flex:1,color:colors.textMid,fontSize:12}, researchGraph:{height:118,borderWidth:1,borderColor:colors.border,borderRadius:radius.lg,backgroundColor:colors.bgDeep,overflow:'hidden',justifyContent:'center',alignItems:'center'}, graphTag:{position:'absolute',bottom:14,color:colors.textMid,fontSize:10}, insightViolet:{borderWidth:1,borderColor:colors.soulLine,borderRadius:radius.lg,backgroundColor:colors.cardBg,padding:spacing.md,gap:spacing.sm}, insightVioletText:{color:colors.textTitle,fontSize:13,}, evRow:{flexDirection:'row',gap:6}, evChip:{color:colors.cyanDim,fontSize:10,paddingHorizontal:8,paddingVertical:4,borderWidth:1,borderColor:colors.border,borderRadius:radius.sm}, formatGrid:{flexDirection:'row',flexWrap:'wrap',gap:9}, formatCard:{width:'47%',padding:13,borderWidth:1,borderColor:colors.border,borderRadius:radius.md,backgroundColor:colors.cardBg,gap:4}, formatCardSel:{borderColor:colors.soulLine}, formatName:{color:colors.cyanSoft,fontSize:13}, formatNameSel:{color:colors.soul}, formatDesc:{color:colors.textLo,fontSize:10.5,}, soulPrimary:{alignItems:'center',justifyContent:'center',backgroundColor:colors.soul,borderRadius:radius.md,paddingVertical:spacing.md}, sourceRow:{flexDirection:'row',alignItems:'center',gap:11,paddingVertical:11,paddingHorizontal:13,borderWidth:1,borderColor:colors.border,borderRadius:radius.md,backgroundColor:colors.cardBg}, sourceRowDim:{opacity:0.7}, sourceName:{color:colors.textTitle,fontSize:13}, sourceNameDim:{color:colors.textMid,fontSize:13}, sourceDesc:{color:colors.textLo,fontSize:10}, sourceCta:{color:colors.cyan,fontSize:11}, sourceSoon:{color:colors.cyanDim,fontSize:10}, reviewLabel:{color:colors.cyanBright,fontSize:11,letterSpacing:0.7,marginBottom:spacing.xs}, mapRow:{flexDirection:'row',alignItems:'center',gap:8}, mapFrom:{color:colors.cyanSoft,fontSize:12}, mapArrow:{color:colors.cyanDim,fontFamily:fontFamilies.readable,fontSize:12}, mapTo:{color:colors.textTitle,fontSize:12}, recMetaRow:{flexDirection:'row',alignItems:'center',gap:6,flexWrap:'wrap'}, recMetaType:{color:colors.cyanSoft,fontSize:11}, recMetaDot:{color:colors.textLo,fontSize:11}, recMeta:{color:colors.textLo,fontSize:11}, recTitle:{color:colors.textTitle,fontSize:17,}, recBody:{borderWidth:1,borderColor:colors.border,borderRadius:radius.md,backgroundColor:colors.cardBg,padding:spacing.md}, recBodyText:{color:colors.textHi,fontSize:12.5,}, iconBtnDanger:{borderColor:colors.clay}, opsStep:{borderWidth:1,borderColor:colors.border,borderRadius:radius.lg,backgroundColor:colors.cardBg,padding:spacing.md,gap:spacing.sm}, opsStepHead:{flexDirection:'row',alignItems:'flex-start',gap:spacing.sm}, opsStepTitle:{flex:1,color:colors.textTitle,fontSize:13.5,}, timeChipMint:{color:colors.mint,fontSize:10,borderWidth:1,borderColor:colors.mint,borderRadius:radius.sm,paddingHorizontal:8,paddingVertical:3,overflow:'hidden'}, timeChipCyan:{color:colors.textMid,fontSize:10,borderWidth:1,borderColor:colors.border,borderRadius:radius.sm,paddingHorizontal:8,paddingVertical:3,overflow:'hidden'}, opsReason:{color:colors.textMid,fontSize:11.5,}, opsStepFoot:{flexDirection:'row',alignItems:'center',gap:spacing.sm}, smallBtn:{marginLeft:'auto',minHeight:44,justifyContent:'center',backgroundColor:colors.cyan,borderRadius:radius.sm,paddingHorizontal:12,paddingVertical:7}, smallBtnText:{color:colors.bgDeep,fontSize:11}, smallBtnGhost:{marginLeft:'auto',minHeight:44,justifyContent:'center',borderWidth:1,borderColor:colors.borderHi,borderRadius:radius.sm,paddingHorizontal:12,paddingVertical:7}, smallBtnGhostText:{color:colors.cyanSoft,fontSize:11}, wikiFloatClear:{flex:1,paddingTop:88}, wikiStatRow:{flexDirection:'row',gap:spacing.sm}, wikiViewToggle:{alignSelf:'stretch'}, wikiStat:{flex:1,flexDirection:'row',alignItems:'baseline',gap:6,borderWidth:1,borderColor:colors.border,borderRadius:radius.md,backgroundColor:colors.cardBg,paddingHorizontal:13,paddingVertical:11}, wikiStatNum:{color:colors.textTitle,fontSize:20}, wikiStatNumCyan:{color:colors.cyan}, wikiStatCap:{color:colors.textLo,fontSize:10.5}, wikiPageOpen:{borderWidth:1,borderColor:colors.borderHi,borderRadius:radius.lg,backgroundColor:colors.cardBg,padding:spacing.md,gap:spacing.sm}, wikiPageHead:{flexDirection:'row',alignItems:'center',gap:7}, wikiPageTitle:{flex:1,color:colors.textTitle,fontSize:13.5}, wikiCaret:{color:colors.cyanDim,fontSize:14}, wikiBody:{color:colors.textHi,fontSize:11.5,}, wikiBacklinkRow:{flexDirection:'row',gap:6,flexWrap:'wrap',alignItems:'center'}, wikiBacklink:{color:colors.cyanSoft,fontSize:12,borderWidth:1,borderColor:colors.soulLine,borderRadius:radius.sm,paddingHorizontal:8,paddingVertical:4,overflow:'hidden'}, wikiPageRow:{borderWidth:1,borderColor:colors.border,borderRadius:radius.md,backgroundColor:colors.cardBg,paddingHorizontal:13,paddingVertical:11,gap:5}, wikiRowHead:{flexDirection:'row',alignItems:'center',gap:7}, wikiRowTitle:{flex:1,color:colors.cyanSoft,fontSize:13}, wikiRowConn:{color:colors.cyanDim,fontSize:9.5}, wikiRowDesc:{color:colors.textLo,fontSize:11}, domainCard:{width:'47%',padding:14,borderWidth:1,borderColor:colors.border,borderRadius:radius.md,backgroundColor:colors.cardBg,gap:8}, domainCardActive:{borderColor:colors.cyan}, domainCardDim:{borderStyle:'dashed',borderColor:colors.borderHi,opacity:0.65}, domainName:{color:colors.textTitle,fontSize:14}, domainNameDim:{color:colors.textMid,fontSize:14}, domainNumRow:{flexDirection:'row',alignItems:'baseline',gap:5}, domainNum:{color:colors.cyanSoft,fontSize:22}, domainNumActive:{color:colors.cyan}, domainNumDim:{color:colors.textLo}, domainUnit:{color:colors.textLo,fontSize:10}, domainSub:{color:colors.cyanDim,fontSize:9.5}, topicCol:{gap:8}, topicRow:{flexDirection:'row',alignItems:'center',gap:9,paddingVertical:10,paddingHorizontal:13,borderWidth:1,borderColor:colors.border,borderRadius:radius.md,backgroundColor:colors.cardBg}, topicDot:{width:6,height:6,borderRadius:3,backgroundColor:colors.cyan}, topicDotDim:{backgroundColor:colors.cyanDim}, topicText:{flex:1,color:colors.textTitle,fontSize:12.5}, topicTextDim:{flex:1,color:colors.textMid,fontSize:12.5}, opsTodayHead:{flexDirection:'row',alignItems:'center',justifyContent:'space-between'}, opsTodayRow:{minHeight:48,flexDirection:'row',alignItems:'center',gap:spacing.sm,paddingVertical:spacing.sm,paddingHorizontal:spacing.md,borderWidth:1,borderColor:colors.border,borderRadius:radius.md,backgroundColor:colors.cardBg}, opsCheck:{width:22,height:22,borderRadius:radius.sm,borderWidth:1,borderColor:colors.borderHi,alignItems:'center',justifyContent:'center'}, opsCheckOn:{backgroundColor:colors.cyan,borderColor:colors.cyan}, opsCheckMark:{color:colors.bgDeep,fontSize:13,fontFamily:fontFamilies.readable}, opsTodayTitle:{flex:1,color:colors.textTitle,fontSize:13,}, opsTodayTitleDone:{color:colors.textLo,textDecorationLine:'line-through'},
  insightsWeeklyLabel:{color:colors.cyanDim,textAlign:'center',fontFamily:m3.font.mono,fontSize:11,letterSpacing:0.7,},
  insightsBars:{flexDirection:'row',alignItems:'flex-end',justifyContent:'center',gap:spacing.xl,paddingTop:spacing.md},
  insightsBarCol:{width:78,alignItems:'center',gap:spacing.xs},
  insightsBarTrack:{height:88,width:34,justifyContent:'flex-end',borderRadius:radius.sm,backgroundColor:colors.bgDeep,overflow:'hidden',borderWidth:1,borderColor:colors.border},
  insightsBarFillMuted:{width:'100%',borderTopLeftRadius:radius.sm,borderTopRightRadius:radius.sm,backgroundColor:colors.borderHi},
  insightsBarFillActive:{width:'100%',borderTopLeftRadius:radius.sm,borderTopRightRadius:radius.sm,backgroundColor:colors.cyan},
  // --- focus timer (Wave 1, daily_focus) ---
  focusStage:{alignItems:'center',justifyContent:'center',paddingVertical:spacing.xl,gap:spacing.sm},
  focusPhase:{color:colors.cyanDim,fontFamily:m3.font.mono,fontSize:8,letterSpacing:1.2,textTransform:'uppercase'},
  focusClock:{color:colors.textTitle,fontSize:64,},
  focusControls:{flexDirection:'row',gap:spacing.sm},
  // --- srs review (Wave 1, language_practice) ---
  srsCard:{minHeight:200,backgroundColor:colors.cardBg,borderWidth:1,borderColor:colors.borderHi,borderRadius:radius.lg,padding:spacing.lg,alignItems:'center',justifyContent:'center',gap:spacing.md},
  srsFaceLabel:{color:colors.cyanDim,fontSize:8,letterSpacing:1.2,textTransform:'uppercase'},
  srsFaceText:{color:colors.textTitle,fontSize:24,textAlign:'center'},
  srsHint:{color:colors.textLo,fontSize:11},
  srsRatingRow:{flexDirection:'row',gap:spacing.xs},
  srsRatingBtn:{flex:1,alignItems:'center',justifyContent:'center',borderColor:colors.borderHi,borderWidth:1,borderRadius:radius.md,paddingVertical:spacing.md},
  srsRatingText:{color:colors.cyanSoft,fontSize:12},
  // --- auth (sign-in / sign-up / reset) deep-space presentation ---
  // Field labels (EMAIL / PASSWORD / BIRTHDATE) sit on the auth gate every user
  // passes; 7px was the smallest text in the app and illegible for low-vision /
  // elderly (the BIRTHDATE label also drives minor-consent gating). Raised to a
  // legible size in line with the surrounding auth text (eyeText 11, helper 11.5).
  authLabel:{color:colors.textMid,fontSize:12,letterSpacing:0.7,textTransform:'uppercase',marginBottom:4},
  authLabelRow:{flexDirection:'row',alignItems:'center',justifyContent:'space-between'},
  eyeBtn:{minWidth:44,minHeight:36,alignItems:'flex-end',justifyContent:'center'},
  eyeText:{color:colors.cyanSoft,fontSize:11},
  providerBtn:{alignItems:'center',justifyContent:'center',borderColor:colors.borderHi,borderWidth:1,borderRadius:radius.md,paddingVertical:spacing.md},
  providerBtnText:{color:colors.cyanSoft,fontSize:13},
  providerRow:{flexDirection:'row',alignItems:'center',justifyContent:'center',gap:8},
  providerBadge:{color:colors.cyanSoft,fontSize:14,fontWeight:'800'},
  btnDisabled:{opacity:0.45},
  authDividerRow:{flexDirection:'row',alignItems:'center',gap:spacing.md,marginVertical:spacing.xs},
  authDividerLine:{flex:1,height:StyleSheet.hairlineWidth,backgroundColor:colors.border},
  authDividerLabel:{color:colors.textLo,fontSize:11,letterSpacing:0.7,textTransform:'uppercase'},
  authDanger:{color:colors.clay,fontSize:12,},
  authHelper:{color:colors.textMid,fontSize:11.5,},
  authLinkRow:{minHeight:44,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:6},
  authForgotRow:{minHeight:44,alignItems:'center',justifyContent:'center'},
  authHelpCard:{borderWidth:1,borderColor:colors.borderHi,borderRadius:radius.md,backgroundColor:colors.cardBg,padding:spacing.md,gap:spacing.sm},
  authHelpTitle:{color:colors.textTitle,fontSize:13},
  authHelpBody:{color:colors.textMid,fontSize:11.5,},
  authToastWrap:{position:'absolute',left:spacing.lg,right:spacing.lg,bottom:spacing.xl,alignItems:'stretch'},
  authToast:{borderWidth:1,borderRadius:radius.md,paddingVertical:spacing.sm,paddingHorizontal:spacing.md},
  authToastInfo:{borderColor:colors.borderHi,backgroundColor:colors.cardBg},
  authToastSuccess:{borderColor:colors.mint,backgroundColor:colors.cardBg},
  authToastDanger:{borderColor:colors.clay,backgroundColor:colors.cardBg},
  authToastText:{color:colors.textHi,fontSize:12.5,},
  // Social-first sign-in (01-auth clone). Hero label / title / subtitle, then
  // provider pills + email-entry floating directly on the gradient (no card).
  authBrand:{color:colors.cyanBright,fontSize:11,letterSpacing:1.8,fontFamily:m3.font.mono,textAlign:'center',marginTop:4},
  authTitle:{color:colors.textTitle,fontSize:22,fontWeight:'700',textAlign:'center'},
  authSub:{color:colors.textMid,fontSize:14,textAlign:'center'},
  authMethods:{gap:11,marginTop:spacing.lg},
  providerPill:{minHeight:52,borderRadius:radius.pill,alignItems:'center',justifyContent:'center',paddingHorizontal:spacing.md},
  providerPillLight:{backgroundColor:deepSpace.providerLightBg,borderWidth:1,borderColor:deepSpace.providerLightLine},
  providerPillDark:{backgroundColor:colors.cardBg,borderWidth:1,borderColor:colors.borderHi},
  providerPillRow:{flexDirection:'row',alignItems:'center',justifyContent:'center',gap:9},
  providerPillTextLight:{color:deepSpace.providerLightFg,fontSize:15,fontWeight:'700'},
  providerPillTextDark:{color:colors.textHi,fontSize:15,fontWeight:'600'},
  providerMarkLight:{color:deepSpace.providerLightFg,fontSize:16,fontWeight:'800'},
  providerMarkDark:{color:colors.textHi,fontSize:16,fontWeight:'800'},
  emailEntry:{minHeight:54,flexDirection:'row',alignItems:'center',justifyContent:'space-between',borderRadius:radius.md,backgroundColor:colors.cardBg,borderWidth:1,borderColor:colors.border,paddingHorizontal:14},
  emailEntryLeft:{flexDirection:'row',alignItems:'center',gap:11},
  emailEntryLabel:{color:colors.textHi,fontSize:15},
  emailEntryArrow:{color:colors.cyanSoft,fontSize:18,fontFamily:fontFamilies.readable},
  authSignUpRow:{minHeight:44,flexDirection:'row',alignItems:'center',justifyContent:'center',flexWrap:'wrap',gap:6,marginTop:spacing.md},
  authSignUpPrompt:{color:colors.textLo,fontSize:13},
  authSignUpCta:{color:colors.cyanSoft,fontSize:13,fontWeight:'700'},
  authLegal:{color:colors.textLo,fontSize:11,textAlign:'center',marginTop:spacing.xl,paddingHorizontal:spacing.md},
  authPrimary:{backgroundColor:colors.cyan,marginTop:2},
  authPrimaryText:{color:colors.bgDeep,fontSize:15,fontWeight:'700'},
  consentGroupLabel:{color:colors.cyanBright,fontSize:12,letterSpacing:0.7,textTransform:'uppercase',marginTop:spacing.xs},
  consentIntro:{color:colors.textMid,fontSize:11.5,},
  consentRow:{flexDirection:'row',alignItems:'flex-start',gap:spacing.sm,minHeight:40,paddingVertical:spacing.xs},
  consentCheckbox:{width:22,height:22,borderRadius:radius.sm,borderWidth:1,borderColor:colors.borderHi,alignItems:'center',justifyContent:'center',marginTop:1},
  consentCheckboxOn:{borderColor:colors.cyan,backgroundColor:colors.cyan},
  consentCheckmark:{color:colors.bgDeep,fontFamily:fontFamilies.readable,fontSize:13,lineHeight:15},
  consentLabel:{flex:1,color:colors.textHi,fontSize:12,},
  consentDivider:{height:1,backgroundColor:colors.border,opacity:0.6,marginVertical:spacing.xs},
  minorBanner:{borderWidth:1,borderLeftWidth:4,borderColor:colors.soulLine,borderRadius:radius.sm,backgroundColor:colors.cardBg,padding:spacing.sm},
  minorBannerText:{color:colors.soul,fontSize:11.5,},
  checklistRow:{flexDirection:'row',alignItems:'center',gap:spacing.sm,minHeight:24},
  checklistDot:{width:8,height:8,borderRadius:4},
  checklistText:{flex:1,fontSize:11.5}});

