#!/usr/bin/env node
/**
 * gen-tokens.mjs — derive data/app/tokens.json from m3-theme.css.
 *
 * m3-theme.css stays the design-token canon (handoff CLAUDE.md rule 3); this
 * script extracts every CSS custom property into a structured JSON mirror so
 * non-CSS consumers (the Expo app, native theming, docs) can read the same
 * values without a CSS parser. Deterministic: same CSS in → same JSON out.
 *
 * Output shape:
 *   { source, palettes: { "<palette>-<scheme>": { "--md-sys-color-*": "#..." } },
 *     root: { ...top-level :root custom props (type scale, shape, motion, sb-*) } }
 *
 * Run from design/proto_rev2:  node tools/gen-tokens.mjs
 * Writes BOTH copies (reference-app/data and ../../public/proto/data) so the
 * tracked deploy copy cannot drift from the handoff canon.
 */
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const APP = path.resolve(HERE, '..', 'reference-app');
const css = readFileSync(path.join(APP, 'm3-theme.css'), 'utf8');

// strip comments to keep the prop regex honest
const clean = css.replace(/\/\*[\s\S]*?\*\//g, '');

// collect custom properties per selector block
const blocks = [...clean.matchAll(/([^{}]+)\{([^{}]*)\}/g)];
const palettes = {};
const root = {};

for (const [, rawSel, body] of blocks) {
  const props = [...body.matchAll(/(--[\w-]+)\s*:\s*([^;]+);/g)];
  if (props.length === 0) continue;
  const sel = rawSel.trim();
  const paletteMatch = sel.match(/data-palette="(\w+)"/);
  const themeMatch = sel.match(/data-theme="(\w+)"/);
  let bucket;
  if (paletteMatch || themeMatch) {
    const key = `${paletteMatch ? paletteMatch[1] : 'cyan'}-${themeMatch ? themeMatch[1] : 'light'}`;
    bucket = palettes[key] = palettes[key] || {};
  } else if (sel.includes(':root')) {
    bucket = root;
  } else {
    continue; // component rules with vars — not token definitions
  }
  for (const [, name, value] of props) bucket[name] = value.trim();
}

const out = {
  source: 'm3-theme.css (generated by tools/gen-tokens.mjs — do not edit by hand)',
  palettes,
  root,
};

const json = JSON.stringify(out, null, 2) + '\n';
const targets = [path.join(APP, 'data', 'app', 'tokens.json')];
const publicCopy = path.resolve(HERE, '..', '..', '..', 'public', 'proto', 'data', 'app', 'tokens.json');
if (existsSync(path.dirname(publicCopy))) targets.push(publicCopy);
for (const t of targets) {
  writeFileSync(t, json);
  console.log('wrote', t);
}
console.log('palette sets:', Object.keys(palettes).join(', '), '| root props:', Object.keys(root).length);
