-- CHC (Cattell-Horn-Carroll) Theory of Cognitive Abilities — verified knowledge sources
-- Batch source: docs/research/batches/chc-cognitive-abilities.md
-- DOIs verified against Crossref / publisher record, May 2026.
-- `verified_at = now()` set at insert; re-verify quarterly.
-- 2nd-Brain treats CHC as Tier A vocabulary only; never as measurement.

insert into public.knowledge_sources
  (title, authors, doi, url, framework, age_range, locale,
   verified_at, summary_ko, summary_en, application_notes)
values
  (
    'Theory of fluid and crystallized intelligence: A critical experiment',
    ARRAY['Raymond B. Cattell'],
    '10.1037/h0046743',
    'https://doi.org/10.1037/h0046743',
    'chc',
    'adult',
    'en',
    now(),
    'Cattell이 일반 지능을 유동지능(Gf — 새로운 추론, 문화 독립)과 결정지능(Gc — 누적된 지식, 문화 의존) 두 개의 일반 요인으로 분리한 최초의 결정적 실험. CHC 이론 계보의 출발점이며 이후 모든 위계적 지능 모델의 토대.',
    'The Gf / Gc split. First empirical demonstration that general intelligence is two distinct general factors: fluid intelligence (novel reasoning, culture-independent) and crystallized intelligence (accumulated knowledge, culture-dependent). The originating paper of what becomes CHC theory.',
    '인지능력 차원의 어휘적 토대로 사용. 점수화·측정 금지. Gf/Gc 어휘는 Advisor의 자기탐색 대화에만 활용.'
  ),
  (
    'Refinement and test of the theory of fluid and crystallized general intelligences',
    ARRAY['John L. Horn','Raymond B. Cattell'],
    '10.1037/h0023816',
    'https://doi.org/10.1037/h0023816',
    'chc',
    'adult',
    'en',
    now(),
    'Horn이 Cattell의 Gf/Gc 모형을 정교화하고 추가 광역 능력(시각 처리·청각 처리·인출·속도)을 발견해 확장한 Horn-Cattell extended Gf-Gc 모형의 핵심 논문. 모든 후속 CHC broad ability의 씨앗.',
    'Refines Gf/Gc and adds broader factor structure. Horn''s expansion identifies additional broad abilities beyond Gf/Gc (visual processing, auditory processing, retrieval, speed). The seed of every later CHC broad ability.',
    'Gv·Ga·Gs·Glr 등 광역 능력 어휘의 1차 출처. 정확한 검사 없이 인플레이션된 추론은 금지.'
  ),
  (
    'Human Cognitive Abilities: A Survey of Factor-Analytic Studies',
    ARRAY['John B. Carroll'],
    '10.1017/CBO9780511571312',
    'https://doi.org/10.1017/CBO9780511571312',
    'chc',
    'adult',
    'en',
    now(),
    'Carroll이 70년에 걸친 461개 요인분석 데이터를 재분석해 세 층위 위계 구조(Stratum III g, Stratum II 약 8개 광역 능력, Stratum I 약 70개 좁은 능력)를 제시한 단행본. 현대 CHC 합의의 경험적 척추. ISBN 0-521-38275-0.',
    'The three-stratum hierarchical synthesis. Carroll reanalyzed 461 factor-analytic datasets from 70 years of intelligence research, producing a hierarchy with g at Stratum III, ~8 broad abilities at Stratum II, and ~70 narrow abilities at Stratum I. The empirical backbone of the modern CHC consensus. ISBN 0-521-38275-0; monograph — no single-paper DOI.',
    '광역 능력이 g 아래에 위치한다는 위계 구조의 근거. 사용자에게 단일 IQ로 환원해 설명하지 말 것.'
  ),
  (
    'CHC theory and the human cognitive abilities project: Standing on the shoulders of the giants of psychometric intelligence research',
    ARRAY['Kevin S. McGrew'],
    '10.1016/j.intell.2008.08.004',
    'https://doi.org/10.1016/j.intell.2008.08.004',
    'chc',
    'adult',
    'en',
    now(),
    'McGrew가 Horn-Cattell 확장 모형과 Carroll의 3층 모형을 공식적으로 통합해 "CHC"라는 합의 명칭을 도입한 논문. WJ, SB5, WAIS 등 현대 검사가 사용하는 정전적 broad ability 분류를 정의.',
    'The formal CHC unification. McGrew explicitly merges Horn-Cattell extended Gf-Gc with Carroll''s three-stratum model and coins "CHC" as the consensus name. Defines the canonical broad-ability taxonomy used by all modern CHC-aligned assessments (WJ, SB5, WAIS-IV/V mappings).',
    '"CHC가 무엇인가"라는 사용자 질문에 가장 압축적으로 답할 수 있는 1차 인용.'
  ),
  (
    'The Cattell-Horn-Carroll theory of cognitive abilities',
    ARRAY['W. Joel Schneider','Kevin S. McGrew'],
    NULL,
    'https://search.worldcat.org/search?q=Contemporary+Intellectual+Assessment+Fourth+Edition',
    'chc',
    'adult',
    'en',
    now(),
    'Flanagan & McDonough 편 Contemporary Intellectual Assessment(4판) 4장. 16개 broad ability와 약 80개 narrow ability를 통합 정리하고 신경인지 증거를 반영. 현재 CHC의 가장 최신 정전 문헌으로 인용됨. 단행본 챕터 — DOI 없음.',
    'The most-current canonical CHC reference. 90-page chapter consolidates 16 broad abilities and ~80 narrow abilities, integrates neurocognitive evidence, and clarifies which broad factors have strongest replication. The textbook citation for "what CHC says today." Book chapter — no single-paper DOI.',
    'Advisor 응답에서 CHC를 학술적으로 안내할 때 인용. 사용자에게는 "Schneider & McGrew 2018 정리에 따르면…" 식으로 인용 가능.'
  ),
  (
    'Multiple intelligences, the Mozart effect, and emotional intelligence: A critical review',
    ARRAY['Lynn Waterhouse'],
    '10.1207/s15326985ep4104_1',
    'https://doi.org/10.1207/s15326985ep4104_1',
    'chc',
    'adult',
    'en',
    now(),
    'MI(다중지능)에 대한 경험적 비판. 23년간 8개 지능이 독립적이라는 peer-reviewed 검증이 없었고 MI 기반 교육의 증분 타당도가 없다고 결론. CHC가 왜 우위에 있는지를 보여주는 대조 문헌.',
    'The empirical critique of MI. Waterhouse argues MI lacks construct validation, no neurocognitive evidence supports the separable "intelligences," and educational applications show no incremental validity over standard cognitive ability assessment. MI is a pedagogical framework, not a tested model of cognition.',
    '사용자가 MI 어휘를 사용할 때 CHC가 왜 더 견고한지 설명할 근거. 단, 사용자 정체성으로의 MI는 존중.'
  ),
  (
    'The science of multiple intelligences theory: A response to Lynn Waterhouse',
    ARRAY['Howard Gardner','Seana Moran'],
    '10.1207/s15326985ep4104_2',
    'https://doi.org/10.1207/s15326985ep4104_2',
    'chc',
    'adult',
    'en',
    now(),
    'Gardner와 Moran의 Waterhouse 비판에 대한 반론. 개념적 정당성은 옹호하나 Waterhouse가 요구한 요인분석·구성 타당도 증거는 제시하지 못함. MI vs CHC 논쟁의 양면을 균형 있게 보여주는 자료.',
    'Gardner''s reply defends MI on conceptual grounds but does not supply the missing factor-analytic / construct-validation evidence Waterhouse demanded. The debate is itself instructive: MI is popular in education but lacks the psychometric backbone CHC provides.',
    'MI 옹호 측 입장을 균형 있게 인용. 사용자에게 양 진영의 논쟁을 소개할 때 사용.'
  ),
  (
    '"General intelligence," objectively determined and measured',
    ARRAY['Charles Spearman'],
    '10.2307/1412107',
    'https://doi.org/10.2307/1412107',
    'chc',
    'adult',
    'en',
    now(),
    'Spearman이 다양한 인지 과제 간 양의 상관(positive manifold)을 관찰해 단일 일반 요인 g와 과제특수 요인 s를 제안한 1904년 원논문. 심리측정적 지능 연구의 역사적 뿌리.',
    'The original g. Spearman observed positive intercorrelations across diverse cognitive tasks ("positive manifold") and proposed a single general factor (g) plus task-specific factors (s). The historical root of psychometric intelligence research.',
    'CHC가 g를 부정하지 않고 g 아래 구조를 명세한다는 점을 설명할 때 인용.'
  ),
  (
    'A special validity study of the Woodcock–Johnson IV: Acting on evidence for specific abilities',
    ARRAY['Christopher R. Niileksela','Matthew R. Reynolds','Timothy Z. Keith','Kevin S. McGrew'],
    '10.1016/B978-0-12-802076-0.00003-7',
    'https://doi.org/10.1016/B978-0-12-802076-0.00003-7',
    'chc',
    'lifespan',
    'en',
    now(),
    'WJ-IV의 CHC broad ability 점수가 일반 지능을 통제한 뒤에도 읽기·수학·쓰기 성취를 추가로 예측함을 보임. broad ability 수준 해석이 단일 g 해석을 넘어 증분 타당도를 갖는다는 경험적 근거.',
    'Demonstrates that WJ-IV broad-ability scores predict reading, math, and writing achievement over and above general intelligence. Establishes that CHC broad abilities have incremental validity — the empirical case for profile-level rather than g-only interpretation.',
    '"왜 단일 IQ가 아니라 프로파일이 의미 있나"라는 질문의 근거. 단, 2nd-Brain은 점수 자체를 생성하지 않음.'
  ),
  (
    'Hierarchical exploratory factor analyses of the Woodcock-Johnson IV Full Test Battery: Implications for CHC application in school psychology',
    ARRAY['Stefan C. Dombrowski','Ryan J. McGill','Gary L. Canivez'],
    '10.1037/spq0000221',
    'https://doi.org/10.1037/spq0000221',
    'chc',
    'lifespan',
    'en',
    now(),
    'WJ-IV의 위계적 탐색적 요인분석 결과 출판사가 제시한 CHC 점수 체계보다 더 적은 광역 요인이 회복된다는 비판적 검토. 단일 검사의 CHC 프로파일 과독해에 대한 중요한 경고.',
    'WJ-IV factor structure scrutiny. Hierarchical EFA recovers fewer broad factors than the publisher''s CHC scoring suggests. A critical perspective: the WJ-IV''s clinically reported subtest groupings may overrepresent the CHC structure in marketing/scoring while the underlying factor solution is sparser.',
    '"CHC 점수가 절대적"이라는 오해 방지용. 균형 잡힌 인용으로 사용.'
  ),
  (
    'Age and sex invariance of the Woodcock-Johnson IV Tests of Cognitive Abilities: Evidence from psychometric network modeling',
    ARRAY['Okan Bulut','Damien C. Cormier','Alexandra M. Aquilina','Hatice C. Bulut'],
    '10.3390/jintelligence9030035',
    'https://doi.org/10.3390/jintelligence9030035',
    'chc',
    'lifespan',
    'en',
    now(),
    'WJ-IV의 CHC 점수가 학령기부터 노년까지의 연령과 성별에 걸쳐 측정 동등성을 유지함을 심리측정 네트워크 모델링으로 입증. 생애 전반 CHC 추론의 정당성 근거.',
    'Measurement invariance for WJ-IV CHC scores across age (school-age through older adult) and sex — critical for cross-age inference using CHC broad-ability vocabulary.',
    '연령대별 사용자 응답에 CHC 어휘를 일관되게 적용해도 되는 근거.'
  ),
  (
    'Test review: Roid, G. H. (2003). Stanford-Binet Intelligence Scales, Fifth Edition (SB:V)',
    ARRAY['Henry L. Janzen','John E. Obrzut','Christine W. Marusiak'],
    '10.1177/082957350401900113',
    'https://doi.org/10.1177/082957350401900113',
    'chc',
    'lifespan',
    'en',
    now(),
    'Stanford-Binet 5가 Gf·Gc·Gv·Gsm·Gq의 5개 CHC broad ability를 언어·비언어 소검사로 어떻게 조작화하는지 리뷰. SB5의 CHC 정렬을 확인하면서도 요인 구조 재현 증거는 혼재됨을 지적.',
    'Stanford-Binet 5 → CHC alignment. Reviews how SB5 operationalizes five CHC broad abilities (Gf, Gc, Gv, Gsm, Gq) via verbal and nonverbal subtests. Confirms SB5 as a CHC-aligned battery while flagging mixed factor-structure replication evidence.',
    '"어떤 검사가 CHC를 따르나" 질문에 대한 답변용 인용.'
  ),
  (
    'Cognitive aging revisited: A cross-sectional analysis of the WAIS-5',
    ARRAY['Emily L. Winter','Brittany A. Dale','Subina Maharjan','Caitlin R. Lando','Caroline M. Larsen','Troy Courville','Alan S. Kaufman'],
    '10.3390/jintelligence13070085',
    'https://doi.org/10.3390/jintelligence13070085',
    'chc',
    'elderly',
    'en',
    now(),
    'WAIS-5(2024)가 Perceptual Reasoning Index를 시각공간(Gv)과 유동추론(Gf)으로 분리해 CHC와 명시적으로 정렬된 첫 Wechsler 개정판임을 확인. 횡단 분석에서 고전적 Gf·Gs 감소와 Gc 보존 패턴 재확인.',
    'WAIS-5 → CHC + aging trajectories. WAIS-5 restructures the Perceptual Reasoning Index into separate Visual Spatial (Gv) and Fluid Reasoning (Gf) indices — explicitly aligning with CHC broad abilities. The cross-sectional aging analysis confirms classic Gf/Gs decline and Gc preservation patterns.',
    'Elder 트랙 노화 내러티브의 가장 최신 인용. "유동·속도는 줄지만 결정은 오래간다"는 표준 표현에 사용.'
  ),
  (
    'Critically reflecting on the origins, evolution, and impact of the Cattell-Horn-Carroll (CHC) model',
    ARRAY['Ryan J. McGill','Stefan C. Dombrowski'],
    '10.1080/08957347.2019.1619561',
    'https://doi.org/10.1080/08957347.2019.1619561',
    'chc',
    'adult',
    'en',
    now(),
    'CHC 모델이 검사 출판 산업에서 상업적으로 채택된 과정과 모든 "CHC 기반" 주장이 동등한 요인분석 증거에 근거하는지에 대한 비판적 검토. CHC 열정에 대한 균형 잡힌 견제 시각.',
    'Critical perspective on CHC''s evolution. Reviews how CHC has been adopted commercially in test publishing and questions whether all "CHC-aligned" claims rest on equally strong factor-analytic evidence. Important balance against uncritical CHC enthusiasm.',
    'CHC를 무비판적으로 사용하지 않도록 가드. 사용자에게 검사 마케팅과 과학적 합의를 구분해 안내.'
  ),
  (
    'A strong dependency between changes in fluid and crystallized abilities in human cognitive aging',
    ARRAY['Elliot M. Tucker-Drob','Javier de la Fuente','Ylva Köhncke','Andreas M. Brandmaier','Lars Nyberg','Ulman Lindenberger'],
    '10.1126/sciadv.abj2422',
    'https://doi.org/10.1126/sciadv.abj2422',
    'chc',
    'elderly',
    'en',
    now(),
    '두 대규모 종단 연구에서 유동지능과 결정지능 변화가 개인 내부에서 강하게 상관됨을 보인 연구. Gf 감소는 Gc 감소(또는 증가 실패)를 예측. "Gf는 떨어지고 Gc는 안정"이라는 교과서 도식을 정련.',
    'Modern longitudinal Gf/Gc aging evidence. Two large longitudinal studies show fluid and crystallized changes are strongly correlated within individuals — losing Gf predicts losing (or failing to gain) Gc. Refines the classic "Gf declines, Gc stable" textbook story into a coupled-trajectory account.',
    'Elder 트랙에서 정직한 노화 내러티브의 핵심 인용. "오직 지혜만 늘어난다"는 약속 금지.'
  ),
  (
    'Comparison between Wechsler and CHC structural models of the K-WAIS-IV',
    ARRAY['Hyunjung Jo','Kwang-Bai Park','Soontae T. Hwang'],
    '10.15842/kjcp.2015.34.3.002',
    'https://doi.org/10.15842/kjcp.2015.34.3.002',
    'chc',
    'adult',
    'ko',
    now(),
    'K-WAIS-IV 표준화 표본(N=1,228)에 대한 확인적 요인분석에서 CHC 구조모형이 Wechsler 4요인 모형보다 적합도가 유의하게 우수함을 보인 한국 자료. Perceptual Reasoning이 Gf와 Gv로 깔끔하게 분리되고 Arithmetic은 Gf와 Gsm에 동시 부하. 한국 사용자에게 CHC가 적절한 프레임임을 보여주는 가장 강력한 단일 증거.',
    'CHC structure replicates better than Wechsler structure in Korean adults. CFA on the K-WAIS-IV normative sample (N=1,228) showed the CHC structural model fit significantly better than the Wechsler four-index model. Specifically, the Perceptual Reasoning Index splits cleanly into Gf and Gv; Arithmetic loads on both Gf and Gsm. The strongest single piece of Korean-context evidence that CHC is the appropriate framework for Korean cognitive ability inference.',
    '한국 사용자에게 CHC 어휘를 사용할 때 1차 근거. 미국 노름을 강요하지 말 것.'
  ),
  (
    'Validity of the K-WAIS-IV short forms',
    ARRAY['Ahyoung Choi','Sangbeom Hong','Kwang-Bai Park','Jeanyung Chey','Soontae T. Hwang','Jungho Kim'],
    '10.15842/kjcp.2014.33.2.011',
    'https://doi.org/10.15842/kjcp.2014.33.2.011',
    'chc',
    'adult',
    'ko',
    now(),
    'K-WAIS-IV 단축형의 타당도를 한국 표본에서 확립한 연구. 한국 성인 지능 평가의 정전 도구로서 K-WAIS-IV의 위상을 뒷받침.',
    'K-WAIS-IV short-form validation in Korean samples. Establishes that abbreviated K-WAIS-IV forms retain reasonable validity. A base citation for "the Korean Wechsler is the canonical adult intelligence assessment in Korea."',
    '한국에서 CHC가 어떤 검사를 통해 운영되는지 사용자에게 안내할 때 인용.'
  ),
  (
    'Age effect of CHC index on K-WAIS-IV',
    ARRAY['Hyunjung Jo','Soontae T. Hwang'],
    '10.22257/kjp.2017.06.36.2.271',
    'https://doi.org/10.22257/kjp.2017.06.36.2.271',
    'chc',
    'lifespan',
    'ko',
    now(),
    '한국 K-WAIS-IV 자료에서 Gc는 성인기 전반에 걸쳐 안정적이고 Gf·Gv·Gsm·Gs는 감소하는 패턴이 재현됨을 보인 연구. 한국 표본에서도 서구의 고전적 Gf 감소 / Gc 보존 도식이 성립.',
    'CHC factor indices across Korean age groups. Shows that in Korean K-WAIS-IV data, Gc remains stable across adulthood while Gf, Gv, Gsm, and Gs decline — replicating the classic Western Gf-decline / Gc-preservation pattern within a Korean sample.',
    '한국 Adult / Elder 트랙의 연령별 내러티브에 사용. 사용자에게 한국 데이터 근거임을 명시.'
  ),
  (
    'Linguistic styles: Language use as an individual difference',
    ARRAY['James W. Pennebaker','Laura A. King'],
    '10.1037/0022-3514.77.6.1296',
    'https://doi.org/10.1037/0022-3514.77.6.1296',
    'chc',
    'adult',
    'en',
    now(),
    'LIWC 스타일 텍스트 특성이 신뢰할 만한 개인차 신호임을 보인 기초 논문. 어휘 폭과 단어 길이가 SAT 점수와 상관된다는 잠정적 단서 — 텍스트에서 Gc로의 행동적 연결 가능성.',
    'The foundational text-as-individual-difference paper. Demonstrates that LIWC-style text features are reliable individual-difference signals, including a factor interpretable as cognitive style. Vocabulary breadth and word-length in student essays correlate with SAT scores — a tentative behavioral link from text to Gc.',
    '저널 텍스트로 CHC 신호를 "추론"하는 정당성 근거, 그러나 측정이 아니라 어휘적 단서임을 강조.'
  ),
  (
    'Words of wisdom: Language use over the life span',
    ARRAY['James W. Pennebaker','Lori D. Stone'],
    '10.1037/0022-3514.85.2.291',
    'https://doi.org/10.1037/0022-3514.85.2.291',
    'chc',
    'lifespan',
    'en',
    now(),
    '3,000명 이상과 문학 코퍼스에서 연령 증가가 인과 구조의 복잡성, 자기 참조 감소, 미래 지향 증가 같은 언어적 인지 복잡성과 연관됨을 보인 연구. 텍스트가 인구 수준에서 결정지능적 성숙을 색인한다는 증거.',
    'Language use changes with age, reflecting cognitive complexity. Across 3,000+ participants and historical literary corpora, increasing age is associated with greater linguistic cognitive complexity (more complex causal structure, fewer self-references, more future-oriented). A signal that text can index aspects of crystallized/cognitive maturity — at the population, not individual, level.',
    '연령대별 글쓰기 변화를 사용자에게 narrate할 때 인용. 개인 단위 추론은 금지.'
  ),
  (
    'The psychological meaning of words: LIWC and computerized text analysis methods',
    ARRAY['Yla R. Tausczik','James W. Pennebaker'],
    '10.1177/0261927X09351676',
    'https://doi.org/10.1177/0261927X09351676',
    'chc',
    'adult',
    'en',
    now(),
    'LIWC 범주가 사고 양식을 포함한 심리 구성과 어떻게 연결되는지 통합한 방법론적 정리. 저널 텍스트로부터 CHC 추론을 시도하는 어휘적 근거를 제공하면서도 LIWC 범주는 인지 양식의 상관일 뿐 인지 능력의 측정이 아님을 명시.',
    'The methodological anchor for LIWC-based text analysis. Synthesizes how LIWC categories map to psychological constructs including thinking styles. Provides the empirical vocabulary for attempting CHC inference from journal text — but explicitly cautions that LIWC categories are correlates of cognitive style, not measures of cognitive ability.',
    '텍스트 기반 trait extraction의 방법론 인용. "스타일 신호이지 능력 점수가 아님"을 명시.'
  ),
  (
    'Confronting a traumatic event: Toward an understanding of inhibition and disease',
    ARRAY['James W. Pennebaker','Sandra K. Beall'],
    '10.1037/0021-843X.95.3.274',
    'https://doi.org/10.1037/0021-843X.95.3.274',
    'chc',
    'adult',
    'en',
    now(),
    '표현적 글쓰기(expressive writing) 패러다임의 기초 논문. 저널링이 심리적 신호를 담을 수 있다는 paradigm을 정초. CHC 직접 출처는 아니지만, 저널 텍스트 분석 자체를 정당화하는 다리 연구.',
    'The foundational expressive-writing study. Anchors the paradigm that journal writing carries psychological signal — see also self-knowledge.md. Not a CHC source per se, but the bridge that justifies analyzing journal text at all.',
    '저널링 자체의 정당성 근거. CHC 추론을 시도해도 좋다는 토대가 되지만, 능력 측정으로 비약 금지.'
  );
