-- Cross-Cultural & East Asian Cultural Psychology — verified knowledge sources
-- Batch source: docs/research/batches/cross-cultural-east-asian.md
-- DOIs verified against Crossref / publisher record, May 2026.
-- `verified_at = now()` set at insert; re-verify quarterly.
-- 2nd-Brain weights cultural constructs as probability priors, not deterministic profiles.
-- Within-culture variance > between-culture variance (Oyserman 2002).

insert into public.knowledge_sources
  (title, authors, doi, url, framework, age_range, locale,
   verified_at, summary_ko, summary_en, application_notes)
values
  (
    'Face and favor: The Chinese power game',
    ARRAY['Kwang-Kuo Hwang'],
    '10.1086/228588',
    'https://doi.org/10.1086/228588',
    'cross_cultural_ea',
    'adult',
    'en',
    now(),
    '유교적 사회 관계에서 face(체면)와 favor(은혜) 교환의 사회심리 모델. 공적/혼합/도구적 관계 유형별로 자원 배분 규칙이 다름을 제시. 한국·중국·일본 사용자가 관계 의무를 설명할 때 어떤 관계 유형인지 식별하는 데 유용.',
    'Sociopsychological model of face-and-favor exchange in Confucian relations. Distinguishes expressive / mixed / instrumental ties and the resource-allocation rules each follows. American Journal of Sociology 92(4), 944-974.',
    'Korean / Japanese / Chinese 사용자가 관계 의무를 설명할 때 어떤 관계 유형인지 먼저 식별. 직장 갈등 분석에 특히 유용.'
  ),
  (
    'Selfhood and identity in Confucianism, Taoism, Buddhism, and Hinduism: Contrasts with the West',
    ARRAY['David Y.-F. Ho'],
    '10.1111/j.1468-5914.1995.tb00269.x',
    'https://doi.org/10.1111/j.1468-5914.1995.tb00269.x',
    'cross_cultural_ea',
    'adult',
    'en',
    now(),
    '유교·도교·불교·힌두교의 자아 개념을 서구와 대조한 이론적 논문. 관계적 자아(relational self)가 동아시아 자아 구성의 핵심임을 정리.',
    'Theoretical paper contrasting selfhood concepts in Confucianism, Taoism, Buddhism, and Hinduism with Western frameworks. Establishes that the relational self is central to East Asian self-construction. Journal for the Theory of Social Behaviour 25(2), 115-139.',
    '동아시아 사용자의 "관계 속 자기" 어휘를 이해하기 위한 배경 인용.'
  ),
  (
    'The deep structure of Confucianism: A social psychological approach',
    ARRAY['Kwang-Kuo Hwang'],
    '10.1080/09552360120116928',
    'https://doi.org/10.1080/09552360120116928',
    'cross_cultural_ea',
    'adult',
    'en',
    now(),
    'Hwang의 유교 심층 구조 분석. 인(仁)·의(義)·예(禮)의 사회심리적 작동 방식을 모델화. Confucian relations 시리즈의 이론적 정점.',
    'Hwang''s social-psychological analysis of Confucian deep structure, modeling how ren (benevolence), yi (righteousness), and li (propriety) operate in social interaction. Asian Philosophy 11(3), 179-204.',
    '유교 윤리 어휘(인의예지)를 사용자 자기성찰에 통합할 때 인용.'
  ),
  (
    'Culture and the self: Implications for cognition, emotion, and motivation',
    ARRAY['Hazel R. Markus','Shinobu Kitayama'],
    '10.1037/0033-295x.98.2.224',
    'https://doi.org/10.1037/0033-295x.98.2.224',
    'cross_cultural_ea',
    'adult',
    'en',
    now(),
    '독립적 자아 vs 상호의존적 자아 구분을 도입한 정전 논문. 동아시아 문화에서 자기는 사회적 관계 속에서 정의되며 인지·정서·동기에 광범위한 영향. 2nd-Brain의 동아시아 사용자 대응에서 가장 자주 참조되는 이론적 닻.',
    'The canonical paper introducing the independent vs interdependent self-construal distinction. In East Asian cultures the self is defined within social relationships, with pervasive effects on cognition, emotion, and motivation. Psychological Review 98(2), 224-253.',
    '한국·일본 사용자에게 서구 빅5/자아 어휘를 적용하기 전 반드시 참조해야 하는 1차 이론.'
  ),
  (
    'The self and social behavior in differing cultural contexts',
    ARRAY['Harry C. Triandis'],
    '10.1037/0033-295x.96.3.506',
    'https://doi.org/10.1037/0033-295x.96.3.506',
    'cross_cultural_ea',
    'adult',
    'en',
    now(),
    'Triandis의 개인주의-집단주의 이론적 정초. 사적 자아·공적 자아·집단적 자아의 세 측면이 문화에 따라 가중치가 다름을 제시. Markus & Kitayama와 함께 교차문화 자아 연구의 양대 산맥.',
    'Triandis''s theoretical foundation for individualism-collectivism. Proposes that private, public, and collective selves carry different weights across cultures. With Markus & Kitayama, one of the two pillars of cross-cultural self research. Psychological Review 96(3), 506-520.',
    '한국 사용자의 "우리/나" 가중치 차이를 설명할 때 1차 이론적 닻.'
  ),
  (
    'Is there a universal need for positive self-regard?',
    ARRAY['Steven J. Heine','Darrin R. Lehman','Hazel R. Markus','Shinobu Kitayama'],
    '10.1037/0033-295x.106.4.766',
    'https://doi.org/10.1037/0033-295x.106.4.766',
    'cross_cultural_ea',
    'adult',
    'en',
    now(),
    'Heine 외(1999). 긍정적 자기존중에 대한 보편적 필요성 주장에 대한 반박. 일본인은 자기증진보다 자기비판적 자기개선 지향이 더 강함을 보임. 일본·한국 사용자에게 서구식 "자존감 높이기" 개입을 강요하지 않을 근거.',
    'Heine et al. (1999). Challenges the claim that positive self-regard is a universal need. Japanese participants show stronger self-critical self-improvement orientation than self-enhancement. Psychological Review 106(4), 766-794.',
    'Japanese/Korean 사용자에게 자존감 증진 개입을 push하지 않을 핵심 근거. Advisor 톤 조정.'
  ),
  (
    'Deviance or uniqueness, harmony or conformity? A cultural analysis',
    ARRAY['Heejung Kim','Hazel R. Markus'],
    '10.1037/0022-3514.77.4.785',
    'https://doi.org/10.1037/0022-3514.77.4.785',
    'cross_cultural_ea',
    'adult',
    'en',
    now(),
    'Kim & Markus(1999). 동일한 행동(예: 독특한 선택)이 미국 맥락에서는 "uniqueness"로, 동아시아 맥락에서는 "deviance"로 해석된다는 점을 실험적으로 보임. 조화와 순응이 동아시아에서 긍정적 가치임을 명시.',
    'Kim & Markus (1999). Shows experimentally that the same behavior (e.g., unique choice) is interpreted as "uniqueness" in American contexts but "deviance" in East Asian contexts. Harmony and conformity carry positive value in East Asia. Journal of Personality and Social Psychology 77(4), 785-800.',
    '한국 사용자가 "남들과 다름"을 부담스러워할 때 병리화하지 않을 근거.'
  ),
  (
    'Rethinking individualism and collectivism: Evaluation of theoretical assumptions and meta-analyses',
    ARRAY['Daphna Oyserman','Heather M. Coon','Markus Kemmelmeier'],
    '10.1037/0033-2909.128.1.3',
    'https://doi.org/10.1037/0033-2909.128.1.3',
    'cross_cultural_ea',
    'adult',
    'en',
    now(),
    '170개 이상 개인주의/집단주의 연구의 메타분석. 미국과 다른 나라 간 효과크기가 종종 미국 내 분산보다 작음을 보임. 결정적 함의: 한국인이 개인주의적 자아를 가졌다고 해서 "한국적 본질"에서 이탈한 것이 아니라 정상 한국 범위 내. Psychological Bulletin 128(1), 3-72.',
    'Meta-analysis of 170+ individualism/collectivism studies. Effect sizes between US and other countries are often smaller than within-US variance. Critical implication: a Korean user with individualistic self-construal is NOT a deviation from "Korean essence" — they are within normal Korean range. Psychological Bulletin 128(1), 3-72.',
    '문화적 본질주의 방지의 핵심 인용. 사용자 개인차를 문화적 일탈로 처리하지 말 것.'
  ),
  (
    'Individualism: A valid and important dimension of cultural differences between nations',
    ARRAY['Ulrich Schimmack','Shigehiro Oishi','Ed Diener'],
    '10.1207/s15327957pspr0901_2',
    'https://doi.org/10.1207/s15327957pspr0901_2',
    'cross_cultural_ea',
    'adult',
    'en',
    now(),
    'Schimmack 외(2005). Hofstede의 개인주의 점수가 응답 양식 인공물을 보정한 후에야 타당함을 보임. Hofstede 단행본을 직접 인용하지 않고 이 논문을 경험적 닻으로 사용해야 하는 근거.',
    'Schimmack, Oishi & Diener (2005). Shows that Hofstede''s IDV scores are valid only after correcting for response-style artifacts. The empirical anchor for citing individualism/collectivism dimensions instead of citing Hofstede directly. Personality and Social Psychology Review 9(1), 17-31.',
    'Hofstede 인용 대신 사용하는 경험적 닻.'
  ),
  (
    'Cheong: The socioemotional grammar of Koreans',
    ARRAY['Sang-Chin Choi','Soo-Hyang Choi'],
    '10.1023/a:1026606217152',
    'https://doi.org/10.1023/a:1026606217152',
    'cross_cultural_ea',
    'adult',
    'en',
    now(),
    '정(情)을 한국인의 사회정서적 문법으로 분석한 정전 논문. 정은 시간이 누적되며 형성되는 정서적 유대이며 단순한 애착이나 의존이 아닌 한국 관계의 핵심 단위. International Journal of Group Tensions 30(1), 69-80.',
    'Choi & Choi (2001). The canonical paper analyzing jeong (정/情) as the socioemotional grammar of Koreans. Jeong is an affective bondedness that accumulates over time — not simple attachment or dependence, but the core unit of Korean relationships. International Journal of Group Tensions 30(1), 69-80.',
    '한국 사용자의 "정 들었다 / 정 떨어졌다" 언어를 코드패던시로 병리화하지 않을 핵심 근거.'
  ),
  (
    'Jeong as the paradigmatic embodiment of compassion (hesed): A critical examination of disparate and dispositional jeong',
    ARRAY['Angella Son'],
    '10.1007/s11089-014-0611-7',
    'https://doi.org/10.1007/s11089-014-0611-7',
    'cross_cultural_ea',
    'adult',
    'en',
    now(),
    'Son(2014). 정을 자비(compassion, hesed)의 패러다임적 구현으로 분석. 분리된 정(disparate jeong)과 기질적 정(dispositional jeong)을 구분하고 한국 관계 윤리의 깊이를 신학·심리학적 관점에서 검토. Pastoral Psychology 63(5-6), 735-747.',
    'Son (2014). Analyzes jeong as the paradigmatic embodiment of compassion (hesed). Distinguishes disparate from dispositional jeong, examining the depth of Korean relational ethics from theological-psychological perspectives. Pastoral Psychology 63(5-6), 735-747.',
    '정의 윤리적·자비적 차원이 표면에 떠오를 때 인용. Advisor 응답에 깊이 부여.'
  ),
  (
    'Naïve psychology of Koreans'' interpersonal mind and behavior in close relationships',
    ARRAY['Sang-Chin Choi','Kibum Kim'],
    '10.1007/0-387-28662-4_16',
    'https://doi.org/10.1007/0-387-28662-4_16',
    'cross_cultural_ea',
    'adult',
    'en',
    now(),
    'Choi & Kim(2006). 한국인의 친밀 관계에서 "우리(we-ness)" 의식의 작동 방식을 분석. "우리 식구", "우리 팀" 같은 표현이 단순한 1인칭 복수가 아니라 자아의 확장임을 보임. Indigenous and Cultural Psychology 16장.',
    'Choi & Kim (2006). Analyzes the operation of we-ness (우리, uri) in Korean close relationships. Shows that expressions like "우리 식구" (our family) or "우리 팀" (our team) are not simple first-person plurals but extensions of self. Chapter 16 in Indigenous and Cultural Psychology.',
    '한국 사용자의 "우리" 어휘를 자기 경계 약화로 코딩하지 않을 1차 근거.'
  ),
  (
    'The influence of Chemyon on facework and conflict styles: Searching for the Korean face and its impact',
    ARRAY['Yongick Kim','Jin-Bok Yang'],
    '10.1016/j.pubrev.2010.09.007',
    'https://doi.org/10.1016/j.pubrev.2010.09.007',
    'cross_cultural_ea',
    'adult',
    'en',
    now(),
    'Kim & Yang(2011). 한국적 체면(chemyon, 體面)의 사회적 차원과 개인적 차원을 구분. 사회적 체면은 회피적 갈등 양식과 명시적으로 상관됨을 실증. 사회적 체면(지위·수행)과 개인적 체면(서구 face에 가까움)을 구분하는 첫 한국 척도. Public Relations Review 37(1), 60-67.',
    'Kim & Yang (2011). Distinguishes social from personal dimensions of Korean chemyon (체면, 體面). Social chemyon explicitly correlates with avoidant conflict styles. The first Korean instrument distinguishing social chemyon (performance, status) from personal chemyon (closer to Western face). Public Relations Review 37(1), 60-67.',
    '한국 사용자의 갈등 회피를 일반화된 사회불안으로 자동 분류하지 않을 근거.'
  ),
  (
    'From Oldboy to Burning: Han in South Korean films',
    ARRAY['Björn Boman'],
    '10.1177/1354067X20922146',
    'https://doi.org/10.1177/1354067X20922146',
    'cross_cultural_ea',
    'adult',
    'en',
    now(),
    'Boman(2020). 한(恨)을 한국 영화 사례로 분석. 한이 보편적이지 않으며 일제 강점기(1910-1945) 전후로 한국 고유의 본질로 후행적으로 투사된 식민지 시대 구성물임을 시사. 본질주의 위험에 대한 경고를 명시. Culture & Psychology 26(4), 919-932.',
    'Boman (2020). Analyzes han (한/恨) through South Korean film cases. Notes that the modern conception of han as a unique Korean essence emerged during/after Japanese colonization (1910-1945) and was retroactively projected as ancient. Explicitly flags essentialism risk. Culture & Psychology 26(4), 919-932.',
    '한 어휘는 사용자가 스스로 끌어올릴 때만 호응. AI가 한국인이라는 이유로 imposing 금지.'
  ),
  (
    'Nunchi across cultures: Cultural interpretation and psychometric validation in South Korea and the United States',
    ARRAY['Sang Yup Kim'],
    '10.1177/10693971251360452',
    'https://doi.org/10.1177/10693971251360452',
    'cross_cultural_ea',
    'adult',
    'both',
    now(),
    'Kim(2026). 눈치(nunchi)의 교차문화 해석과 한국·미국 표본 심리측정적 검증. 눈치가 한국 고유의 초능력이 아니라 양 문화 모두에서 측정 가능하며 적응적(민감성)·부적응적(과잉 모니터링) 양면을 가짐을 실증. 트레이드 단행본(Hong 2019) 대신 인용해야 하는 경험적 닻. Cross-Cultural Research.',
    'Kim (2026). Cross-cultural interpretation and psychometric validation of nunchi (눈치) in South Korean and American samples. Demonstrates nunchi is not uniquely Korean but measurable in both cultures, with both adaptive (sensitivity) and maladaptive (over-monitoring) dimensions. The empirical anchor to cite instead of the trade book (Hong 2019). Cross-Cultural Research.',
    '눈치 어휘를 사용할 때 1차 인용. 한국 사용자에게 의무가 아니라 기술로 프레이밍.'
  ),
  (
    'Amae — A key concept for understanding Japanese personality structure',
    ARRAY['Takeo Doi'],
    '10.2117/psysoc.1962.1',
    'https://doi.org/10.2117/psysoc.1962.1',
    'cross_cultural_ea',
    'adult',
    'en',
    now(),
    'Doi(1962). 일본인 성격 구조 이해의 핵심 개념으로 아마에(甘え)를 도입한 정전 논문. 친밀한 타인에게 응석을 기대하는 편안한 의존이 일본 관계의 핵심 정서임을 분석. Psychologia 5(1), 1-7.',
    'Doi (1962). The canonical paper introducing amae (甘え) as a key concept for understanding Japanese personality structure. Analyzes comfortable presumed dependence on intimate others as a core emotion of Japanese relationships. Psychologia 5(1), 1-7.',
    '일본 사용자의 의존 행동을 서구 anxious attachment로 자동 분류하지 않을 근거.'
  ),
  (
    'Amae in Japan and the United States: An exploration of a "culturally unique" emotion',
    ARRAY['Yu Niiya','Phoebe C. Ellsworth','Susumu Yamaguchi'],
    '10.1037/1528-3542.6.2.279',
    'https://doi.org/10.1037/1528-3542.6.2.279',
    'cross_cultural_ea',
    'adult',
    'en',
    now(),
    'Niiya 외(2006). 미국 참가자가 상황적 맥락이 제시되면 아마에 등가 감정을 인식함을 실증. 아마에가 일본에만 있는 것이 아니라 다르게 가치화·라벨링되는 것임을 보여줌. 본질주의 비판의 핵심 근거. Emotion 6(2), 279-295.',
    'Niiya, Ellsworth & Yamaguchi (2006). Empirically demonstrates that American participants recognize amae-equivalent emotions when given the situational frame — the construct is not Japan-exclusive, it is differently valued and labeled. A key critique of cultural essentialism. Emotion 6(2), 279-295.',
    '일본 사용자의 amae 행동을 관계 자산으로 검증하고 미숙한 의존으로 코딩하지 않을 근거.'
  ),
  (
    'Further clarifications of the concept of amae in relation to dependence and attachment',
    ARRAY['Susumu Yamaguchi'],
    '10.1159/000075367',
    'https://doi.org/10.1159/000075367',
    'cross_cultural_ea',
    'adult',
    'en',
    now(),
    'Yamaguchi(2004). 아마에를 의존·애착과 구분해 명료화. 아마에는 단순한 의존이 아니라 특정 관계적 기대 구조를 동반하는 정서이며 적절한 사회적 맥락에서 적응적임을 정리. Human Development 47(1), 28-33.',
    'Yamaguchi (2004). Further clarifies amae in distinction from dependence and attachment. Amae is not simple dependence but an emotion with specific relational expectation structure, adaptive in appropriate social contexts. Human Development 47(1), 28-33.',
    'amae를 attachment 이론으로 환원하지 않을 이론적 정리.'
  ),
  (
    'Tatemae/Honne',
    ARRAY['Jane M. Bachnik'],
    '10.1002/9781405165518.wbeost004',
    'https://doi.org/10.1002/9781405165518.wbeost004',
    'cross_cultural_ea',
    'adult',
    'en',
    now(),
    'Bachnik(2007). Blackwell Encyclopedia of Sociology의 honne(本音)/tatemae(建前) 표제 — 내면 감정과 외부 표현의 일본적 구분을 정의. 백과사전 표제이므로 정의 목적으로만 사용. 측정 가능한 심리 구성으로서의 honne/tatemae 증거 기반은 amae보다 얇음.',
    'Bachnik (2007). The Blackwell Encyclopedia of Sociology entry on honne (本音) / tatemae (建前) — defining the Japanese distinction between inner feeling and outer expression. Encyclopedia entry; use for definitional purposes only. The empirical evidence base for honne/tatemae as a measurable psychological construct (vs. a folk-cultural distinction) is thinner than for amae.',
    '일본 사용자가 honne/tatemae 분리를 보고할 때 위선이 아니라 기능적이라고 설명할 때 인용.'
  ),
  (
    'Cultural variation in affect valuation',
    ARRAY['Jeanne L. Tsai','Brian Knutson','Helene H. Fung'],
    '10.1037/0022-3514.90.2.288',
    'https://doi.org/10.1037/0022-3514.90.2.288',
    'cross_cultural_ea',
    'adult',
    'en',
    now(),
    'Tsai 외(2006). 정서 가치 평가의 문화 변이를 정전적으로 정리. 동아시아 문화에서는 차분하고 평화로운 저각성 긍정 정서를 이상으로 삼고 서구에서는 흥분된 고각성 긍정 정서를 이상으로 삼음을 실증. 일본 사용자에게 고에너지 "thriving" 프레임을 강요하지 않을 근거. JPSP 90(2), 288-307.',
    'Tsai, Knutson & Fung (2006). Canonical paper on cultural variation in affect valuation. East Asian cultures idealize low-arousal positive affect (calm, peaceful), while Western cultures idealize high-arousal positive affect (excited). The basis for not pushing high-energy "thriving" framings on Japanese users. JPSP 90(2), 288-307.',
    'Japanese (and many Korean) 사용자의 차분한 안녕 상태를 결손으로 코딩하지 않을 근거.'
  ),
  (
    'The Korean indigenous psychology approach: Theoretical considerations and empirical applications',
    ARRAY['Uichol Kim','Young-Shin Park','Donghyun Park'],
    '10.1111/j.1464-0597.1999.tb00065.x',
    'https://doi.org/10.1111/j.1464-0597.1999.tb00065.x',
    'cross_cultural_ea',
    'adult',
    'en',
    now(),
    'Kim·Park·Park(1999). 한국 토착심리학 접근의 이론적 정초. 한국적 자아·관계·동기 구성을 서구 수입 이론이 아니라 한국 사회·역사 맥락에서 출발해 이해해야 함을 논증. Applied Psychology 48(4), 451-464.',
    'Kim, Park & Park (1999). Theoretical foundation for the Korean Indigenous Psychology approach. Argues that Korean self/relationship/motivation constructions must be understood from Korean social-historical context, not by importing Western theories. Applied Psychology: An International Review 48(4), 451-464.',
    '한국 토착심리학 접근이 필요한 사용자 질문에 1차 인용.'
  ),
  (
    'Culture, identity consistency, and subjective well-being',
    ARRAY['Eunkook M. Suh'],
    '10.1037/0022-3514.83.6.1378',
    'https://doi.org/10.1037/0022-3514.83.6.1378',
    'cross_cultural_ea',
    'adult',
    'en',
    now(),
    'Suh(2002). 한국(집단주의) 참가자의 역할 간 정체성 일관성은 미국 참가자보다 안녕과 약하게 상관됨을 실증. 단일하고 일관된 자아 내러티브를 한국 사용자에게 강요하지 않을 직접 증거. 2nd-Brain에 특히 중요. JPSP 83(6), 1378-1391.',
    'Suh (2002). Shows Korean (collectivist) participants'' identity consistency across roles correlates with wellbeing less strongly than for American participants. Direct evidence against forcing a single-coherent-self narrative onto Korean users. Particularly load-bearing for 2nd-Brain. JPSP 83(6), 1378-1391.',
    '한국 사용자에게 "진정한 자아" / "일관된 자기" 프레임을 push하지 않을 핵심 근거.'
  ),
  (
    'Immigration, acculturation, and adaptation',
    ARRAY['John W. Berry'],
    '10.1111/j.1464-0597.1997.tb01087.x',
    'https://doi.org/10.1111/j.1464-0597.1997.tb01087.x',
    'cross_cultural_ea',
    'adult',
    'en',
    now(),
    'Berry(1997). 이주·문화접변·적응의 정전 이론. 통합·동화·분리·주변화 네 가지 문화접변 전략을 정리. 디아스포라·이중문화 한국 사용자 이해의 1차 이론적 닻. Applied Psychology 46(1), 5-34.',
    'Berry (1997). The canonical theory of immigration, acculturation, and adaptation. Introduces the four acculturation strategies: integration, assimilation, separation, marginalization. The primary theoretical anchor for understanding diasporic/bicultural Korean users. Applied Psychology 46(1), 5-34.',
    '디아스포라 사용자의 문화접변 전략을 표면화하되 강제하지 않을 때 인용.'
  ),
  (
    'Acculturation: Living successfully in two cultures',
    ARRAY['John W. Berry'],
    '10.1016/j.ijintrel.2005.07.013',
    'https://doi.org/10.1016/j.ijintrel.2005.07.013',
    'cross_cultural_ea',
    'adult',
    'en',
    now(),
    'Berry(2005). 1997 이론의 업데이트. 두 문화에서 성공적으로 살아가는 통합 전략의 적응적 우위를 강화. 단, 사회적 수용 조건이 충족되어야 함을 명시. International Journal of Intercultural Relations 29(6), 697-712.',
    'Berry (2005). Update of the 1997 theory. Reinforces the adaptive advantage of the integration strategy for living successfully in two cultures, conditional on social acceptance. International Journal of Intercultural Relations 29(6), 697-712.',
    '이중문화 사용자의 적응 평가에서 통합을 목표로 push하지 않고 자기보고된 전략을 존중할 때 인용.'
  ),
  (
    'Bicultural Identity Integration (BII): Components and psychosocial antecedents',
    ARRAY['Verónica Benet-Martínez','Jana Haritatos'],
    '10.1111/j.1467-6494.2005.00337.x',
    'https://doi.org/10.1111/j.1467-6494.2005.00337.x',
    'cross_cultural_ea',
    'adult',
    'en',
    now(),
    'Benet-Martínez & Haritatos(2005). Bicultural Identity Integration(BII) 구성요소와 심리사회적 선행 요인을 정리. 이중문화 정체성을 통합형(blended) vs 갈등형(conflicted) 연속체로 측정. 낮은 BII 사용자는 통합 압박이 아니라 이중 트랙 정체성 검증이 도움이 됨. Journal of Personality 73(4), 1015-1050.',
    'Benet-Martínez & Haritatos (2005). Establishes Bicultural Identity Integration (BII) components and psychosocial antecedents. Measures bicultural identity on a blended-vs-conflicted continuum. Low-BII users benefit from validation of dual-track identity rather than integration pressure. Journal of Personality 73(4), 1015-1050.',
    '낮은 BII 사용자에게 통합을 목표로 push하지 않을 핵심 근거. 한국계 디아스포라 응답에 직접 적용.'
  ),
  (
    'Korean American college students'' language practices and identity positioning: "Not Korean, but not American"',
    ARRAY['Hyun-Sook Kang'],
    '10.1080/15348458.2013.818473',
    'https://doi.org/10.1080/15348458.2013.818473',
    'cross_cultural_ea',
    'young_adult',
    'en',
    now(),
    'Kang(2013). 한국계 미국인 대학생의 언어 실천과 정체성 위치 부여를 분석. "한국인도 아니고 미국인도 아닌" 정체성이 자기 일관적이고 안정적인 위치임을 기록. 디아스포라 정체성을 "결손" 또는 "전환 중" 상태로 코딩하지 않을 근거. Journal of Language, Identity & Education 12(4), 248-261.',
    'Kang (2013). Analyzes Korean American college students'' language practices and identity positioning. Documents the "not Korean, but not American" framing as a stable, self-coherent identity position. The basis for not coding diaspora identity as "deficit" or "in transition." Journal of Language, Identity & Education 12(4), 248-261.',
    '"둘 다 아닌" 정체성을 가진 한국계 사용자의 자기 정의를 검증할 때 인용.'
  );
