-- Dual-Process Theory (System 1 / System 2 — Cognitive Style) — verified knowledge sources
-- Batch source: docs/research/batches/dual-process-theory.md
-- DOIs verified against Crossref / publisher record, May 2026.
-- `verified_at = now()` set at insert; re-verify quarterly.
-- 2nd-Brain treats dual-process as cognitive-style descriptor, NOT validated taxonomy.
-- Citable evidence is Kahneman (2003) + Stanovich/Evans/Frederick stack — NOT the trade book.

insert into public.knowledge_sources
  (title, authors, doi, url, framework, age_range, locale,
   verified_at, summary_ko, summary_en, application_notes)
values
  (
    'Judgment under uncertainty: Heuristics and biases',
    ARRAY['Amos Tversky','Daniel Kahneman'],
    '10.1126/science.185.4157.1124',
    'https://doi.org/10.1126/science.185.4157.1124',
    'dual_process',
    'adult',
    'en',
    now(),
    '휴리스틱과 편향 프로그램의 원논문. 이중 처리 라벨링 이전이지만 경험적 토대를 제공 — 사람들이 대표성·가용성·기준점 같은 인지적 지름길을 사용하고 그 결과가 규범 규칙과 체계적으로 어긋남을 보임. 이후 모든 이중처리 이론의 증거 기반.',
    'The origin paper for the heuristics-and-biases program. Predates dual-process labelling but establishes the empirical floor: people use cognitive shortcuts (representativeness, availability, anchoring) that systematically diverge from normative rules. All later dual-process theorizing builds on this evidence base.',
    '사용자가 자기 판단에 편향이 있는지 자문할 때 인용. 단, 진단이 아니라 자기관찰의 어휘로 사용.'
  ),
  (
    'The need for cognition',
    ARRAY['John T. Cacioppo','Richard E. Petty'],
    '10.1037/0022-3514.42.1.116',
    'https://doi.org/10.1037/0022-3514.42.1.116',
    'dual_process',
    'adult',
    'en',
    now(),
    'Need for Cognition(NFC) — 노력이 드는 사고를 즐기고 추구하는 안정적 성향 — 을 도입한 기초 논문. 2nd-Brain이 저널 텍스트에서 추론하고자 하는 구성에 가장 가까운 개념: 능력 점수가 아니라 양식 선호.',
    'The dispositional/individual-difference anchor. Introduces Need for Cognition (NFC) — the stable tendency to engage in and enjoy effortful thinking. The construct closest to what 2nd-Brain actually wants to infer from journal text: not a capacity score, but a style preference.',
    'NFC는 "System 1/2 인간"보다 안전한 어휘. 인지 양식 추론의 1차 닻.'
  ),
  (
    'The empirical case for two systems of reasoning',
    ARRAY['Steven A. Sloman'],
    '10.1037/0033-2909.119.1.3',
    'https://doi.org/10.1037/0033-2909.119.1.3',
    'dual_process',
    'adult',
    'en',
    now(),
    '두 개의 질적으로 구분되는 추론 시스템(연합적 vs 규칙 기반)에 대한 최초의 체계적 경험적 논변. Stanovich/Evans의 "System 1/2" 라벨링에 선행하지만 이후 이중처리 주장을 정당화하는 분석철학적 척추.',
    'The first systematic empirical case for two qualitatively distinct reasoning systems (associative vs rule-based). Pre-dates Stanovich/Evans labeling as "System 1 / System 2" but is the analytic philosophy spine that makes the later dual-process claim defensible.',
    '이중처리 어휘를 사용할 때 학술적 출처로 인용. 단순 이분법으로 환원 금지.'
  ),
  (
    'Individual differences in reasoning: Implications for the rationality debate?',
    ARRAY['Keith E. Stanovich','Richard F. West'],
    '10.1017/S0140525X00003435',
    'https://doi.org/10.1017/S0140525X00003435',
    'dual_process',
    'adult',
    'en',
    now(),
    '"System 1"과 "System 2"가 문헌에 용어로 진입한 논문. Stanovich와 West가 구분을 공식화하고 개인차 자료에 근거를 둠. 2nd-Brain의 핵심 함의: 사람마다 System-1 출력을 무효화하는 성향이 안정적으로 다르고 이 차이가 인지 능력·사고 성향·실생활 판단 질과 상관됨.',
    'Where "System 1" and "System 2" enter the literature as terms. Stanovich & West formalize the distinction (later popularized by Kahneman) and ground it in individual-differences data. The crucial finding for 2nd-Brain: people differ stably in their tendency to override System-1 outputs, and this difference correlates with cognitive ability, thinking dispositions, and real-world judgment quality.',
    '"System 1/2"이라는 표현의 학술적 출처. Kahneman 단행본 대신 인용.'
  ),
  (
    'Representativeness revisited: Attribute substitution in intuitive judgment',
    ARRAY['Daniel Kahneman','Shane Frederick'],
    '10.1017/CBO9780511808098.004',
    'https://doi.org/10.1017/CBO9780511808098.004',
    'dual_process',
    'adult',
    'en',
    now(),
    '메커니즘 논문. 어려운 질문을 받으면 System 1이 더 쉬운 질문으로 조용히 대체(attribute substitution)해 그것에 답한다는 모델. 저널링에 직접 관련: 사용자가 "내가 행복한가" 같은 깊은 질문을 "지금 기분이 어떤가" 같은 쉬운 대용으로 답하는 패턴.',
    'The mechanism paper. Introduces attribute substitution: when asked a hard question, System 1 silently substitutes an easier one and answers that. The cleanest model of how intuitive judgment fails — directly relevant to journaling, where users often "answer" deep questions about themselves via easier proxy questions.',
    'Advisor가 사용자의 자기성찰 깊이를 점검하는 핵심 어휘. 단, 진단 톤 금지.'
  ),
  (
    'A perspective on judgment and choice: Mapping bounded rationality',
    ARRAY['Daniel Kahneman'],
    '10.1037/0003-066X.58.9.697',
    'https://doi.org/10.1037/0003-066X.58.9.697',
    'dual_process',
    'adult',
    'en',
    now(),
    'Kahneman의 학술적 종합(노벨 강연 각색본). 인기서 8년 전에 출간된 시스템 1/2 모델의 인용 가능한 학술 버전 — 접근성, 노력, 모니터링 실패 개념을 정리. 2nd-Brain은 이 논문을 인용하지 트레이드 단행본은 인용하지 않음.',
    'Kahneman''s own academic synthesis (Nobel address adaptation), eight years before the popular book. The citable version of the System 1 / System 2 model — accessibility, effort, monitoring failures. Cite this, not the trade book.',
    'System 1/2를 학술적으로 인용할 때 표준 출처. Thinking, Fast and Slow 단행본 인용 금지.'
  ),
  (
    'Dual-processing accounts of reasoning, judgment, and social cognition',
    ARRAY['Jonathan St. B. T. Evans'],
    '10.1146/annurev.psych.59.103006.093629',
    'https://doi.org/10.1146/annurev.psych.59.103006.093629',
    'dual_process',
    'adult',
    'en',
    now(),
    'Annual Review 통합. 추론·판단·사회 인지·학습 전반의 이중처리 가족을 정리하고 "이중처리"가 하나의 이론이 아니라 관련 모델들의 가족임을 명확히 함. 2nd-Brain에 대한 중요한 경고: 이들을 "System 1/2"로 과잉 통일하지 말 것.',
    'The Annual Review consolidation. Maps the entire dual-process family (across reasoning, judgment, social cognition, learning) and clarifies that "dual-process" is not one theory but a family of related models. Important caveat for 2nd-Brain: do not over-unify these as "System 1 / System 2" — that''s one labeling choice among several.',
    '이중처리를 단일 이론으로 단순화하지 않는 균형 인용.'
  ),
  (
    'Cognitive reflection and decision making',
    ARRAY['Shane Frederick'],
    '10.1257/089533005775196732',
    'https://doi.org/10.1257/089533005775196732',
    'dual_process',
    'adult',
    'en',
    now(),
    'Cognitive Reflection Test(CRT) — 직관적 응답을 무효화하는 성향을 측정하는 가장 널리 쓰이는 3문항 행동 척도. 유명한 "bat-and-ball" 문항이 여기 수록. CRT는 일반 인지 능력과 중간 정도 상관되지만 휴리스틱·편향 과제 수행, 시간 간 선택의 인내, 위험 선호 예측에 독립 분산 추가.',
    'The Cognitive Reflection Test (CRT) — the most-used 3-item behavioral measure of disposition to override intuitive responses. The "bat-and-ball" item lives here. CRT correlates moderately with general cognitive ability but adds independent variance for predicting heuristics-and-biases performance, patience in intertemporal choice, and risk preferences.',
    '2nd-Brain은 CRT를 제품 내에서 운영하지 않음. 인지적 인색함이 측정 가능한 개인차라는 증거로만 인용.'
  ),
  (
    'The Cognitive Reflection Test as a predictor of performance on heuristics-and-biases tasks',
    ARRAY['Maggie E. Toplak','Richard F. West','Keith E. Stanovich'],
    '10.3758/s13421-011-0104-1',
    'https://doi.org/10.3758/s13421-011-0104-1',
    'dual_process',
    'adult',
    'en',
    now(),
    'CRT의 증분 타당도 증거. 두 연구에 걸쳐 CRT가 지능·집행기능·사고 성향 위에 휴리스틱·편향 과제 수행을 추가로 예측. CRT가 측정하는 것은 능력이 아니라 분석적 처리에 들어갈 의향임을 확립.',
    'CRT incremental-validity evidence. Across two studies CRT predicted heuristics-and-biases task performance over and above intelligence, executive function, and thinking dispositions — establishing that CRT measures something distinct (the willingness to engage analytic processing, not raw capacity).',
    'CRT가 측정하는 것이 능력이 아니라 양식임을 명시할 때 인용.'
  ),
  (
    'Assessing miserly information processing: An expansion of the Cognitive Reflection Test',
    ARRAY['Maggie E. Toplak','Richard F. West','Keith E. Stanovich'],
    '10.1080/13546783.2013.844729',
    'https://doi.org/10.1080/13546783.2013.844729',
    'dual_process',
    'adult',
    'en',
    now(),
    'CRT-2: 수학·수치 혼입을 줄인 4문항 확장. 방법론적으로 유용 — CRT가 측정하는 것이 수학 능력이 아니라 인지적 인색함(cognitive miserliness), 즉 System 1이 제공한 첫 답을 검토 없이 수용하는 성향임을 재확인.',
    'CRT-2: a 4-item extension reducing math/numeracy confound. Confirms that what CRT measures isn''t math ability but cognitive miserliness — the tendency to accept the first answer System 1 supplies without checking.',
    '인지적 인색함 어휘를 사용할 때의 출처. 사용자에게는 결함이 아니라 양식으로 설명.'
  ),
  (
    'Everyday consequences of analytic thinking',
    ARRAY['Gordon Pennycook','Jonathan A. Fugelsang','Derek J. Koehler'],
    '10.1177/0963721415604610',
    'https://doi.org/10.1177/0963721415604610',
    'dual_process',
    'adult',
    'en',
    now(),
    '분석적 사고 양식이 무엇을 예측하는가에 대한 정리. 종교적 불신, 초자연 회의, 도덕 판단 패턴, 정치 태도를 지능과 독립적으로 예측. 2nd-Brain에 직접 관련: 인지 양식은 고립된 특성이 아니라 사용자의 가치·신념·선택 묘사 방식 전반에 영향.',
    'The "what does analytic style predict?" anchor. Reviews evidence that analytic cognitive style predicts religious disbelief, paranormal skepticism, moral judgment patterns, and political attitudes — independently of intelligence. Direct relevance for 2nd-Brain: cognitive style isn''t an isolated trait, it shapes how users describe values, beliefs, and choices in journal text.',
    '인지 양식이 가치/신념 표현과 어떻게 얽히는지 사용자에게 설명할 때 인용.'
  ),
  (
    'Criterion validity of cognitive reflection for predicting job performance and training proficiency: A meta-analysis',
    ARRAY['Inmaculada Otero','Jesús F. Salgado','Silvia Moscoso'],
    '10.3389/fpsyg.2021.668592',
    'https://doi.org/10.3389/fpsyg.2021.668592',
    'dual_process',
    'adult',
    'en',
    now(),
    'CRT의 메타분석적 타당도. CRT가 일반 인지 능력 검사와 견줄 만한 효과 크기로 직무 성과와 훈련 결과를 예측함을 확립. 2nd-Brain은 CRT를 사용하지 않지만 분석적 사고 성향이 실생활 결과를 갖는다는 증거로만 인용.',
    'Meta-analytic validity for CRT. Establishes CRT predicts job performance and training outcomes with effect sizes comparable to general cognitive ability tests. Cited only as evidence that analytic-thinking disposition has real-world consequences — not as endorsement of using CRT inside 2nd-Brain.',
    '분석적 사고 성향이 실생활 결과에 의미 있다는 근거로만 사용.'
  ),
  (
    'Two is not always better than one: A critical evaluation of two-system theories',
    ARRAY['Gideon Keren','Yaacov Schul'],
    '10.1111/j.1745-6924.2009.01164.x',
    'https://doi.org/10.1111/j.1745-6924.2009.01164.x',
    'dual_process',
    'adult',
    'en',
    now(),
    '인지과학 내부의 첫 주요 비판. "두 시스템" 프레임이 과소 명세돼 있고 제안된 이분법들(빠름/느림, 자동/통제, 연합/규칙, 진화적 옛것/새것)이 깔끔하게 함께 변하지 않는다고 지적. 두 시스템 이론화가 반증 불가능해질 위험.',
    'The first major critique from inside cognitive science. Argues that the "two systems" framing is under-specified: the proposed dichotomies (fast/slow, automatic/controlled, associative/rule-based, evolutionary-old/new) don''t cleanly co-vary. Two-systems theorizing risks becoming unfalsifiable.',
    '이중처리 이론을 정설로 제시하지 않는 균형 인용.'
  ),
  (
    'Dual-process theories of higher cognition: Advancing the debate',
    ARRAY['Jonathan St. B. T. Evans','Keith E. Stanovich'],
    '10.1177/1745691612460685',
    'https://doi.org/10.1177/1745691612460685',
    'dual_process',
    'adult',
    'en',
    now(),
    '옹호자들의 초기 비판에 대한 응답. 원래의 "System 1/2" 속성 집단 다수가 오해의 소지가 있었음을 인정하고 핵심 구분(Type 1 = 자율적, Type 2 = 작업기억 의존)은 살아남는다고 주장. 엄격한 "두 시스템" 프레임을 명시적으로 포기하고 "Type 1/2 처리"라는 더 약한 주장을 선호.',
    'The defenders'' response to early critiques. Concedes that many of the original "System 1 / System 2" attribute clusters were misleading; argues the core distinction (Type 1 = autonomous, Type 2 = working-memory-dependent) survives. They explicitly abandon the strict "two systems" framing and prefer "Type 1 / Type 2 processing" — a softer claim about processes, not architectural modules.',
    '"시스템"이 아니라 "처리 유형"으로 어휘 정련. Advisor 문구에 반영.'
  ),
  (
    'The mythical number two',
    ARRAY['David E. Melnikoff','John A. Bargh'],
    '10.1016/j.tics.2018.02.001',
    'https://doi.org/10.1016/j.tics.2018.02.001',
    'dual_process',
    'adult',
    'en',
    now(),
    '가장 결정적인 현대 비판. 이중처리 이론을 뒷받침하는 네 가지 핵심 이분법(비의도/의도, 통제불가/통제가능, 자율/인지부하 민감, 무의식/의식)이 이론이 예측하는 것처럼 경험적으로 함께 변하지 않음을 보임. 결론: 과학적으로 의미 있는 "둘"은 없으며 이분법은 연구 프레임으로서 수명이 다한 민속심리학적 추상.',
    'The most consequential modern critique. Argues the four "core" dichotomies underlying dual-process theory (unintentional/intentional, uncontrollable/controllable, autonomous/cognitive-load-sensitive, unconscious/conscious) do not empirically co-vary as the theory predicts. Conclusion: there is no scientifically meaningful "two" — the binary is a folk-psychological abstraction that has outlived its usefulness as a research framework.',
    '이중처리를 정설로 약속하지 않는 핵심 인용.'
  ),
  (
    'On dual- and single-process models of thinking',
    ARRAY['Wim De Neys'],
    '10.1177/1745691620964172',
    'https://doi.org/10.1177/1745691620964172',
    'dual_process',
    'adult',
    'en',
    now(),
    '현재 논쟁 상태의 종합. 단순한 "System 1 빠르고 틀림, System 2 느리고 맞음" 그림에 반하는 증거 검토: 사람들은 종종 숙고 전에 정답(논리적·확률적)을 직관함. 단일처리 및 혼합 모델을 제안. 2nd-Brain이 이중처리 프레임을 과도하게 약속하지 않도록 막는 인용.',
    'The current-state-of-debate synthesis. Reviews evidence against the simple "System 1 fast & wrong, System 2 slow & right" picture: people often intuit the correct (logical/probabilistic) answer first before deliberation. Proposes single-process and hybrid models. The citation that prevents 2nd-Brain from over-promising the dual-process frame.',
    '"더 많이 생각하는 것이 항상 더 낫다"는 메시지 금지의 근거.'
  ),
  (
    'Culture and systems of thought: Holistic versus analytic cognition',
    ARRAY['Richard E. Nisbett','Kaiping Peng','Incheol Choi','Ara Norenzayan'],
    '10.1037/0033-295X.108.2.291',
    'https://doi.org/10.1037/0033-295X.108.2.291',
    'dual_process_cultural',
    'adult',
    'en',
    now(),
    '교차문화 기준선. 동아시아(전체론적·맥락 의존적·변증법적) vs 서구(분석적·규칙 기반·형식논리적) 인지의 체계적 차이를 기록. 2nd-Brain 한국 사용자에게 전제 프레임: "System 1 vs System 2" 이분법 자체가 서구 분석적 인지의 산물. 전체론적 사고는 "덜 System 2"가 아니라 다른 추론 양식.',
    'The cross-cultural baseline. Documents systematic East Asian (holistic, context-dependent, dialectical) vs Western (analytic, rule-based, formal-logical) cognition differences. For 2nd-Brain Korean users this is the prerequisite framing: the "System 1 vs System 2" dichotomy is itself a Western analytic-cognition product. Holistic thinking is not "less System 2" — it is a different reasoning mode.',
    '한국 사용자에게 인지 양식 추론을 적용하기 전 반드시 참조.'
  ),
  (
    'Individual differences in analytic versus holistic thinking',
    ARRAY['Incheol Choi','Minkyung Koo','Jong An Choi'],
    '10.1177/0146167206298568',
    'https://doi.org/10.1177/0146167206298568',
    'dual_process_cultural',
    'adult',
    'both',
    now(),
    'Analysis-Holism Scale(AHS) — 미국과 한국 표본에서 구성·검증된 24문항 분석↔전체론 인지 양식 척도. 한국인과 한의대생이 미국인보다 holism 점수가 높음. 한국 사용자에게 CRT 식 측정보다 문화적으로 더 적절한 가장 가까운 검증된 도구.',
    'The Analysis-Holism Scale (AHS) — a 24-item validated measure of analytic ↔ holistic cognitive style, constructed and validated across American and Korean samples. Koreans and Korean-medicine students score higher than Americans on holism. The closest validated Korean cognitive-style instrument and more culturally appropriate for Korean users than CRT-style measures.',
    '한국 사용자의 인지 양식 어휘 1차 닻. 분석/전체론 축이 직관/분석 축보다 우선.'
  ),
  (
    'Thinking across cultures: Implications for dual processes',
    ARRAY['Emma E. Buchtel','Ara Norenzayan'],
    '10.1093/acprof:oso/9780199230167.003.0010',
    'https://doi.org/10.1093/acprof:oso/9780199230167.003.0010',
    'dual_process_cultural',
    'adult',
    'en',
    now(),
    '교차문화 심리학의 전체론/분석론 구분을 이중처리 이론과 연결한 다리 챕터. 서구 이중처리가 "직관적"이라 부르는 것이 동아시아 "전체론적"과 불완전하게 대응함을 논증 — 겹치지만 동일하지 않음. 전체론적 사고는 많은 맥락(특히 관계 추론)에서 빠르면서도 규범적으로 적절할 수 있음.',
    'The bridge chapter linking cultural-psychology holistic/analytic distinction to dual-process theory. Argues that what Western dual-process research calls "intuitive" maps imperfectly onto East Asian "holistic" — they overlap but aren''t identical. Holistic thinking can be both fast and normatively appropriate in many contexts (e.g., relational reasoning).',
    '한국 사용자의 빠른 전체론적 판단을 "직관적이므로 검토 필요"로 자동 분류하지 않도록 가드.'
  ),
  (
    'Dispositional differences in cognitive motivation: The life and times of individuals varying in need for cognition',
    ARRAY['John T. Cacioppo','Richard E. Petty','Jeffrey A. Feinstein','W. Blair G. Jarvis'],
    '10.1037/0033-2909.119.2.197',
    'https://doi.org/10.1037/0033-2909.119.2.197',
    'dual_process',
    'adult',
    'en',
    now(),
    '약 100개 연구를 통합한 NFC 리뷰. NFC는 "System 1 vs System 2 인간"보다 경험적으로 더 안전한 구성 — 이분법이 아니라 연속적 개인차이며 태도 형성, 설득 취약성, 정보 탐색, 의사결정 질을 예측. 2nd-Brain의 인지 양식 추론에 가장 안전한 닻.',
    'The NFC review synthesizing ~100 studies. NFC is a more empirically secure construct than "System 1 vs System 2 person": it''s a continuous individual difference, not a binary, and predicts attitude formation, persuasion susceptibility, information search, and decision quality. For 2nd-Brain, NFC is the safer construct to anchor cognitive-style inference on than System 1/2.',
    '2nd-Brain trait extraction의 이중처리 차원 추론은 NFC 어휘를 1차로 사용.'
  );
