// User-supplied HustleK portraits, 2026-10-08. Static requires keep Metro/native bundles identical.
export const HUSTLEK_EXPRESSIONS = {
  A01: { key: "neutral", source: require("../../../assets/hustlek/png/A01-neutral.png") as number },
  A02: { key: "soft-smile", source: require("../../../assets/hustlek/png/A02-soft-smile.png") as number },
  A03: { key: "eye-smile", source: require("../../../assets/hustlek/png/A03-eye-smile.png") as number },
  A04: { key: "broad-grin", source: require("../../../assets/hustlek/png/A04-broad-grin.png") as number },
  A05: { key: "laugh", source: require("../../../assets/hustlek/png/A05-laugh.png") as number },
  A06: { key: "hearty-laugh", source: require("../../../assets/hustlek/png/A06-hearty-laugh.png") as number },
  A07: { key: "proud", source: require("../../../assets/hustlek/png/A07-proud.png") as number },
  A08: { key: "playful-smirk", source: require("../../../assets/hustlek/png/A08-playful-smirk.png") as number },
  A09: { key: "shy-smile", source: require("../../../assets/hustlek/png/A09-shy-smile.png") as number },
  A10: { key: "relieved", source: require("../../../assets/hustlek/png/A10-relieved.png") as number },
  A11: { key: "grateful", source: require("../../../assets/hustlek/png/A11-grateful.png") as number },
  A12: { key: "delighted", source: require("../../../assets/hustlek/png/A12-delighted.png") as number },
  B01: { key: "attentive", source: require("../../../assets/hustlek/png/B01-attentive.png") as number },
  B02: { key: "focused", source: require("../../../assets/hustlek/png/B02-focused.png") as number },
  B03: { key: "determined", source: require("../../../assets/hustlek/png/B03-determined.png") as number },
  B04: { key: "thoughtful", source: require("../../../assets/hustlek/png/B04-thoughtful.png") as number },
  B05: { key: "curious", source: require("../../../assets/hustlek/png/B05-curious.png") as number },
  B06: { key: "skeptical", source: require("../../../assets/hustlek/png/B06-skeptical.png") as number },
  B07: { key: "hesitant", source: require("../../../assets/hustlek/png/B07-hesitant.png") as number },
  B08: { key: "puzzled", source: require("../../../assets/hustlek/png/B08-puzzled.png") as number },
  B09: { key: "embarrassed", source: require("../../../assets/hustlek/png/B09-embarrassed.png") as number },
  B10: { key: "apologetic", source: require("../../../assets/hustlek/png/B10-apologetic.png") as number },
  B11: { key: "expectant", source: require("../../../assets/hustlek/png/B11-expectant.png") as number },
  B12: { key: "unimpressed", source: require("../../../assets/hustlek/png/B12-unimpressed.png") as number },
  C01: { key: "mild-surprise", source: require("../../../assets/hustlek/png/C01-mild-surprise.png") as number },
  C02: { key: "startled", source: require("../../../assets/hustlek/png/C02-startled.png") as number },
  C03: { key: "shocked", source: require("../../../assets/hustlek/png/C03-shocked.png") as number },
  C04: { key: "disbelief", source: require("../../../assets/hustlek/png/C04-disbelief.png") as number },
  C05: { key: "frightened", source: require("../../../assets/hustlek/png/C05-frightened.png") as number },
  C06: { key: "nervous", source: require("../../../assets/hustlek/png/C06-nervous.png") as number },
  C07: { key: "worried", source: require("../../../assets/hustlek/png/C07-worried.png") as number },
  C08: { key: "sad", source: require("../../../assets/hustlek/png/C08-sad.png") as number },
  C09: { key: "teary", source: require("../../../assets/hustlek/png/C09-teary.png") as number },
  C10: { key: "crying", source: require("../../../assets/hustlek/png/C10-crying.png") as number },
  C11: { key: "sobbing", source: require("../../../assets/hustlek/png/C11-sobbing.png") as number },
  C12: { key: "disappointed", source: require("../../../assets/hustlek/png/C12-disappointed.png") as number },
  D01: { key: "irritated", source: require("../../../assets/hustlek/png/D01-irritated.png") as number },
  D02: { key: "angry", source: require("../../../assets/hustlek/png/D02-angry.png") as number },
  D03: { key: "clenched-teeth", source: require("../../../assets/hustlek/png/D03-clenched-teeth.png") as number },
  D04: { key: "frustrated", source: require("../../../assets/hustlek/png/D04-frustrated.png") as number },
  D05: { key: "disapproving", source: require("../../../assets/hustlek/png/D05-disapproving.png") as number },
  D06: { key: "disgusted", source: require("../../../assets/hustlek/png/D06-disgusted.png") as number },
  D07: { key: "cynical", source: require("../../../assets/hustlek/png/D07-cynical.png") as number },
  D08: { key: "assertive", source: require("../../../assets/hustlek/png/D08-assertive.png") as number },
  D09: { key: "tired", source: require("../../../assets/hustlek/png/D09-tired.png") as number },
  D10: { key: "sleepy", source: require("../../../assets/hustlek/png/D10-sleepy.png") as number },
  D11: { key: "yawning", source: require("../../../assets/hustlek/png/D11-yawning.png") as number },
  D12: { key: "peaceful", source: require("../../../assets/hustlek/png/D12-peaceful.png") as number },
} as const;

export type HustleKExpressionId = keyof typeof HUSTLEK_EXPRESSIONS;
